import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import api from '../api';
import toast from 'react-hot-toast';
import {useAuth} from '../context/AuthContext';
import {useWorkWrite} from './Workflows';
export default function WorkSettings(){
 const {can}=useAuth(),[data,setData]=useState(null),[users,setUsers]=useState([]),[runs,setRuns]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),write=useWorkWrite();
 const load=()=>{api.get('/work/settings').then(r=>setData(r.data)).catch(e=>setError(e.response?.data?.error||'Could not load settings'));api.get('/work/jobs/status').then(r=>setRuns(r.data)).catch(()=>{});};
 useEffect(()=>{load();api.get('/work/options?kind=tickets').then(r=>setUsers(r.data.users)).catch(()=>{});},[]);
 const set=(key,value)=>setData(d=>({...d,value:{...d.value,[key]:value}}));
 const change=(group,i,key,value)=>set(group,data.value[group].map((v,n)=>n===i?{...v,[key]:value}:v));
 async function save(){setBusy(true);try{const r=await write('PUT','/work/settings',{version:data.version,value:data.value});setData(r);toast.success('Work settings saved');}catch(e){toast.error(e.response?.data?.error||'Could not save');}finally{setBusy(false);}}
 async function run(){setBusy(true);try{const r=await write('POST','/work/jobs/run',{});toast.success(`${r.generated} occurrences created; ${r.escalated} in-app escalations; ${r.catch_up_pending} templates still catching up`);load();}catch(e){toast.error(e.response?.data?.error||'Scheduled run failed');}finally{setBusy(false);}}
 if(error)return <p role="alert">{error}</p>;if(!data)return <p>Loading work settings…</p>;
 const edit=can('work_settings','edit');
 return <div className="space-y-5"><h2 className="text-xl font-bold">Work settings</h2><p>Changes apply to new work. Existing tasks and ticket targets retain their saved requirements. Archive options to keep their history.</p><Link className="text-blue-700 underline" to="/admin/roles">Configure role permissions and scopes</Link>
  <fieldset disabled={!edit||busy} className="space-y-5">
   <div className="card space-y-2"><h3 className="font-semibold">Workflow rules</h3>{Object.entries({task_review_required:'New tasks require review',task_evidence_required:'New tasks require a completion file',requester_can_close:'Requester may close a resolved ticket',requester_can_reopen:'Requester may reopen a ticket with a reason',pause_waiting:'New ticket timers pause while waiting for information',notifications_enabled:'In-app workflow notifications',escalations_enabled:'In-app target escalations'}).map(([key,label])=><label key={key} className="flex gap-2"><input type="checkbox" checked={data.value[key]} onChange={e=>set(key,e.target.checked)}/>{label}</label>)}<p className="text-sm text-gray-500">Targets use elapsed clock minutes, not business hours. Reopening starts a new target cycle. External email, SMS and push are not sent by these workflows.</p></div>
   {['priorities','categories'].map(group=><section className="card space-y-3" key={group}><h3 className="font-semibold capitalize">{group}</h3>{data.value[group].map((o,i)=><div key={o.id} className="border rounded p-3 space-y-2"><label className="block text-sm">Name<input className="input" value={o.label} onChange={e=>change(group,i,'label',e.target.value)}/></label><label className="flex gap-2"><input type="checkbox" checked={o.active} onChange={e=>change(group,i,'active',e.target.checked)}/>Available for new work</label>{group==='categories'&&<><label className="block text-sm">Route to responsible employee<select className="select" value={o.assignee_id||''} onChange={e=>change(group,i,'assignee_id',Number(e.target.value)||null)}><option value="">Unassigned — manager triage</option>{users.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label><div className="grid sm:grid-cols-2 gap-3">{['response_minutes','resolution_minutes'].map(key=><label key={key} className="text-sm">{key==='response_minutes'?'Response target (minutes)':'Resolution target (minutes)'}<input className="input" type="number" min="1" max="525600" placeholder="No target" value={o[key]||''} onChange={e=>change(group,i,key,e.target.value?Number(e.target.value):null)}/></label>)}</div><label className="block text-sm">Escalation recipients<select multiple className="select" value={(o.escalation_ids||[]).map(String)} onChange={e=>change(group,i,'escalation_ids',Array.from(e.target.selectedOptions,x=>Number(x.value)))}>{users.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></label><p className="text-xs">Recipients must also have permission to view the ticket.</p></>}</div>)}<button className="btn btn-secondary" onClick={()=>set(group,[...data.value[group],{id:'option_'+crypto.randomUUID().replaceAll('-','').slice(0,12),label:'New '+(group==='categories'?'category':'priority'),active:true,...(group==='categories'?{assignee_id:null,response_minutes:null,resolution_minutes:null,escalation_ids:[]}: {})}])}>Add {group==='categories'?'category':'priority'}</button></section>)}
   <button className="btn btn-primary" onClick={save}>Save settings</button>
  </fieldset>
  <section className="card space-y-3"><h3 className="font-semibold">Scheduled runs</h3><p className="text-sm">Occurrences are generated by a scheduled job, never by opening a screen. Catch-up processes up to 31 dates per template per run. Paused days are skipped on resume. Monthly dates beyond a month's end fall on its last day.</p>{edit&&<button className="btn btn-secondary" disabled={busy} onClick={run}>Run scheduled work now</button>}<p>Last completed run: {runs.find(r=>r.finished_at)?new Date(runs.find(r=>r.finished_at).finished_at).toLocaleString():'No completed run recorded'}</p><p className="text-sm text-gray-500">A scheduler must be configured for automatic recurrence and escalation. This screen supports a manual run for testing.</p></section>
 </div>;
}
