import {Children,cloneElement,isValidElement,useEffect,useId,useRef,useState} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import api from '../api';
import {useAuth} from '../context/AuthContext';
import Modal from '../components/Modal';
import toast from 'react-hot-toast';

const names={tasks:'Delegation',templates:'Checklist templates',occurrences:'Checklists',tickets:'Help Tickets'};
const modules={tasks:'delegations',templates:'checklists',occurrences:'checklists',tickets:'help_tickets'};
const states={pending:'Assigned',in_progress:'In Progress',blocked:'Blocked',submitted:'Submitted for Review',approved:'Completed',rejected:'Returned',open:'Open',assigned:'Assigned',waiting:'Waiting for Information',resolved:'Resolved',closed:'Closed',cancelled:'Cancelled'};
const day=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Kolkata',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const blankItem=()=>({id:crypto.randomUUID(),section:'',label:'',instructions:'',required:true,evidence:'none',allow_na:false});
const localTime=iso=>iso?new Date(new Date(iso).getTime()-new Date(iso).getTimezoneOffset()*60000).toISOString().slice(0,16):'';
const prettyDate=s=>s?new Date(s).toLocaleString():'Not set';
function Field({label,children}){const id=useId();return <div className="block text-sm space-y-1"><label htmlFor={id} className="font-medium text-gray-700">{label}</label>{Children.map(children,child=>isValidElement(child)&&['input','textarea','select'].includes(child.type)?cloneElement(child,{id}):child)}</div>;}
function Check({label,value,onChange}){return <label className="flex gap-2 items-center text-sm"><input type="checkbox" checked={!!value} onChange={e=>onChange(e.target.checked)}/>{label}</label>;}
export function useWorkWrite(){
 const pending=useRef(new Map());
 return async(method,url,body)=>{const fingerprint=JSON.stringify([method,url,body]);let key=pending.current.get(fingerprint);if(!key){key=crypto.randomUUID();pending.current.set(fingerprint,key);}const result=await api({method,url,data:body,headers:{'Idempotency-Key':key}});pending.current.delete(fingerprint);return result.data;};
}
export default function Workflows({kind:initialKind='tasks'}){
 const {user,can,canManagePermissions}=useAuth(),[searchParams,setSearchParams]=useSearchParams();
 const [kind,setKind]=useState(initialKind),[data,setData]=useState({rows:[],total:0}),[options,setOptions]=useState(null),[error,setError]=useState('');
 const [page,setPage]=useState(1),[search,setSearch]=useState(''),[status,setStatus]=useState(()=>searchParams.get('status')||''),[scope,setScope]=useState(()=>['mine','given','all'].includes(searchParams.get('scope'))?searchParams.get('scope'):'mine'),[sort,setSort]=useState('newest'),[overdue,setOverdue]=useState(searchParams.get('overdue')==='1'),[today,setToday]=useState(searchParams.get('today')==='0'?false:initialKind==='occurrences'),[revision,refresh]=useState(0);
 const [selected,setSelected]=useState(null),[form,setForm]=useState(null),[busy,setBusy]=useState(false),[note,setNote]=useState(''),[answers,setAnswers]=useState({}),[proof,setProof]=useState([]),[internal,setInternal]=useState(false),[assignment,setAssignment]=useState(''),[deadline,setDeadline]=useState(''),[assignBranch,setAssignBranch]=useState(''),[reviewer,setReviewer]=useState(''),[legacy,setLegacy]=useState(null);
 const write=useWorkWrite(),detailRequest=useRef(0),uploadKeys=useRef(new WeakMap());
 useEffect(()=>{detailRequest.current++;setSelected(null);setData({rows:[],total:0});},[kind]);
 useEffect(()=>{setKind(initialKind);setPage(1);setSelected(null);},[initialKind]);
 useEffect(()=>{let cancelled=false;setOptions(null);api.get('/work/options',{params:{kind}}).then(r=>{if(!cancelled)setOptions(r.data);}).catch(e=>{if(!cancelled)setError(e.response?.data?.error||'Could not load choices');});return()=>{cancelled=true;};},[kind]);
 useEffect(()=>{
  let cancelled=false;setError('');
  const timeout=setTimeout(()=>api.get(`/work/${kind}`,{params:{page,limit:20,search,status,scope,sort,active:searchParams.get('active')||undefined,review:searchParams.get('review')||undefined,overdue:overdue?'1':undefined,today:today&&kind==='occurrences'?'1':undefined}}).then(r=>{if(!cancelled)setData(r.data);}).catch(e=>{if(!cancelled)setError(e.response?.data?.error||'Could not load work');}),200);
  return()=>{cancelled=true;clearTimeout(timeout);};
 },[kind,page,search,status,scope,sort,overdue,today,revision,searchParams.get('active'),searchParams.get('review')]);
 async function open(id){const request=++detailRequest.current;try{const {data:r}=await api.get(`/work/${kind}/${id}`);if(request!==detailRequest.current)return;setSelected(r);setAnswers(r.work_meta?.answers||{});setProof(r.work_meta?.evidence||[]);setNote('');setAssignment(r.assigned_to||'');setDeadline(localTime(r.work_meta?.due_at));setAssignBranch(r.branch_id||'');setReviewer(r.work_meta?.reviewer_id||user.id);setLegacy(null);}catch(e){toast.error(e.response?.data?.error||'Could not open record');}}
 useEffect(()=>{if(searchParams.get('record'))open(searchParams.get('record'));},[kind,searchParams.get('record')]);
 function close(){detailRequest.current++;setSelected(null);if(searchParams.has('record'))setSearchParams({});}
 function filter(setter,value){setter(value);setPage(1);}
 async function act(action,extra={}){if(busy)return;setBusy(true);try{await write('POST',`/work/${kind}/${selected.id}/actions`,{action,version:selected.work_version,note,...extra});toast.success('Saved');await open(selected.id);refresh(v=>v+1);}catch(e){toast.error(e.response?.data?.error||'Save failed; retry or refresh');}finally{setBusy(false);}}
 function fresh(target=kind,link=null){
  const definition={title:'',instructions:'',items:[blankItem()],assignees:[],review_required:false,reviewer_id:'',effective_from:day(),schedule:{frequency:'daily',start:day(),end:null,due_time:'18:00',timezone:'Asia/Kolkata',missed:'catch_up',days:[1],month_day:1}};
  setForm({kind:target,title:'',description:'',branch_id:link?.branch_id||options?.own_branch||'',assigned_to:'',due_at:'',priority:options?.priorities?.find(p=>p.id==='medium'&&p.active)?.id||options?.priorities?.find(p=>p.active)?.id||'',category:options?.categories?.find(c=>c.active)?.id||'general',review_required:options?.defaults?.review_required??true,evidence_required:options?.defaults?.evidence_required??true,reviewer_id:user.id,collaborators:[],definition,link:link?{kind,id:link.id}:undefined});
 }
 async function saveForm(e){e.preventDefault();if(busy)return;setBusy(true);try{
  const payload={...form,branch_id:Number(form.branch_id),assigned_to:form.assigned_to?Number(form.assigned_to):undefined,reviewer_id:Number(form.reviewer_id)||null};
  if(form.kind==='tasks')payload.due_at=new Date(form.due_at).toISOString();
  const r=await write(form.id?'PUT':'POST',`/work/${form.kind}${form.id?'/'+form.id:''}`,payload);
  toast.success(form.kind==='templates'?'Template saved; scheduled jobs create its occurrences':'Created');setForm(null);refresh(v=>v+1);
  if(form.kind===kind)await open(r.id);else toast.success('Linked ticket created. The original work status is unchanged.');
 }catch(e){toast.error(e.response?.data?.error||e.message||'Could not save');}finally{setBusy(false);}}
 async function upload(file){if(!file)return;setBusy(true);try{const fd=new FormData();fd.append('file',file);if(internal)fd.append('internal','true');let key=uploadKeys.current.get(file);if(!key){key=crypto.randomUUID();uploadKeys.current.set(file,key);}const {data:r}=await api.post(`/work/${kind}/${selected.id}/files`,fd,{headers:{'Content-Type':'multipart/form-data','Idempotency-Key':key}});setSelected(s=>({...s,files:[...s.files.filter(f=>f.id!==r.id),r]}));toast.success('File attached. Select it below as evidence.');}catch(e){toast.error(e.response?.data?.error||'Upload failed');}finally{setBusy(false);}}
 async function download(file){try{const {data:r}=await api.get(`/work/files/${file.id}/download`);const a=document.createElement('a');a.href=r.url;a.rel='noopener';a.target='_blank';a.click();}catch(e){toast.error(e.response?.data?.error||'Could not open attachment');}}
 const update=(key,value)=>setForm(f=>({...f,[key]:value}));
 const dupdate=(key,value)=>setForm(f=>({...f,definition:{...f.definition,[key]:value}}));
 const supdate=(key,value)=>setForm(f=>({...f,definition:{...f.definition,schedule:{...f.definition.schedule,[key]:value}}}));
 const choiceUsers=options?.users||[],uoptions=<><option value="">Select employee</option>{choiceUsers.map(u=><option value={u.id} key={u.id}>{u.name}</option>)}</>;
 const isMine=selected?.assigned_to===user.id,meta=selected?.work_meta||{};
 const active=selected&&!['approved','cancelled','submitted','closed'].includes(selected.status);
 const actionButton=(label,action,extra={},disabled=false)=><button type="button" key={action} disabled={busy||disabled} className="btn btn-primary" onClick={()=>act(action,extra)}>{label}</button>;
 return <div className="space-y-4">
  <div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-bold">{names[kind]}</h2><p className="text-sm text-gray-500">Your role controls which records and actions are available.</p></div><nav className="flex flex-wrap gap-3 text-sm"><Link to="/delegations">My tasks</Link><Link to="/checklists">Today's checklists</Link><Link to="/help-tickets">My tickets</Link>{can('work_settings')&&<Link to="/work-settings">Work settings</Link>}{canManagePermissions&&<Link to="/admin/roles">Role permissions</Link>}</nav></div>
  {['templates','occurrences'].includes(kind)&&<div className="flex flex-wrap gap-2"><button className="btn btn-secondary" onClick={()=>{setKind('occurrences');setToday(true);setSelected(null);setPage(1);}}>Today's checklists</button><button className="btn btn-secondary" onClick={()=>{setKind('occurrences');setToday(false);setSelected(null);setPage(1);}}>Checklist history</button>{can('checklists','create')&&<button className="btn btn-secondary" onClick={()=>{setKind('templates');setScope('all');setSelected(null);setPage(1);}}>Templates</button>}</div>}
  <div className="card flex flex-wrap gap-3 items-end">
   <Field label="Search"><input aria-label="Search work" className="input" value={search} onChange={e=>filter(setSearch,e.target.value)} placeholder="Search title"/></Field>
   <Field label="View"><select className="select" value={scope} onChange={e=>filter(setScope,e.target.value)}><option value="mine">My work</option><option value="given">Created by me</option><option value="all">All permitted work</option></select></Field>
   <Field label="Status"><select className="select" value={status} onChange={e=>filter(setStatus,e.target.value)}><option value="">All statuses</option>{Object.entries(states).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Field>
   <Field label="Sort"><select className="select" value={sort} onChange={e=>filter(setSort,e.target.value)}><option value="newest">Newest first</option><option value="oldest">Oldest first</option><option value="title">Title</option>{['tasks','occurrences'].includes(kind)&&<option value="due">Due soonest</option>}</select></Field>
   {['tasks','occurrences'].includes(kind)&&<Check label="Overdue only" value={overdue} onChange={v=>filter(setOverdue,v)}/>}
   {kind!=='occurrences'&&can(modules[kind],'create')&&<button disabled={!options} className="btn btn-primary" onClick={()=>fresh()}>Create {kind==='tasks'?'task':kind==='tickets'?'ticket':'template'}</button>}
   <button className="btn btn-secondary" onClick={()=>refresh(v=>v+1)}>Refresh</button>
  </div>
  {error&&<p role="alert" className="text-red-700">{error}</p>}
  <div className="grid md:grid-cols-2 xl:grid-cols-3 gap-3">{data.rows.map(row=><button key={row.id} className="card text-left min-w-0 hover:border-blue-400" onClick={()=>open(row.id)}><div className="font-semibold break-words">{row.title}</div><div className="text-sm mt-2">{kind==='templates'?(row.work_meta?.state||'Earlier template — publish a version to schedule'):states[row.status]||row.status}{row.overdue&&<span className="ml-2 text-red-700 font-semibold">Overdue</span>}</div><div className="text-xs text-gray-500 mt-1">{row.assigned_to_name||'Unassigned'} · {row.branch_name||'Branch not assigned'}</div>{(row.due_at||row.work_meta?.due_at)&&<p className="text-sm">Due {prettyDate(row.due_at||row.work_meta.due_at)}</p>}{row.work_meta?.blocker&&<p className="text-sm text-amber-700">Blocked: {row.work_meta.blocker}</p>}</button>)}</div>
  {(searchParams.get('active')==='1'||searchParams.get('review')==='1')&&<p className="text-sm text-blue-700">{searchParams.get('review')==='1'?'Showing submissions you can review.':'Showing unfinished work.'} <button className="underline" onClick={()=>{const p=new URLSearchParams(searchParams);p.delete('active');p.delete('review');p.delete('status');setSearchParams(p);setStatus('');setPage(1);}}>Clear dashboard filter</button></p>}
  {!error&&!data.rows.length&&<p className="card text-gray-500">No work matches this view.</p>}
  <div className="flex items-center gap-4"><button className="btn btn-secondary" disabled={page===1} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page} · {data.total} records</span><button className="btn btn-secondary" disabled={page*20>=data.total} onClick={()=>setPage(p=>p+1)}>Next</button></div>

  <Modal isOpen={!!selected} onClose={close} title={selected?.title||'Work details'} wide>
   {selected&&<fieldset disabled={busy} className="space-y-4">
    <p className="font-semibold">{states[selected.status]||selected.status} · Record #{selected.id}</p><p className="whitespace-pre-wrap">{selected.description}</p>
    {['tasks','tickets'].includes(kind)&&<p className="text-sm">Priority: {selected.priority||meta.priority||'Not recorded'}{selected.category?` · Category: ${options?.categories.find(c=>c.id===selected.category)?.label||selected.category}`:''}</p>}
    {(meta.due_at||selected.due_at)&&<p>Due: {prettyDate(meta.due_at||selected.due_at)}</p>}
    {meta.blocker&&<p className="bg-amber-50 p-3">Blocker: {meta.blocker}</p>}
    {meta.resolution&&<p className="bg-green-50 p-3">Resolution: {meta.resolution}</p>}
    {meta.link&&<p>Linked {meta.link.kind==='tasks'?'task':'checklist'} #{meta.link.id}. Its status is managed separately.</p>}
    {kind==='tickets'&&meta.opened_at&&<p className="text-sm">Response target: {meta.response_minutes?`${meta.response_minutes} minutes`:'Not configured'} · Resolution target: {meta.resolution_minutes?`${meta.resolution_minutes} minutes`:'Not configured'}{meta.pause_started?' · Timers paused while waiting for information':''}</p>}
    {selected.definition&&<div className="space-y-3"><p className="font-semibold">Template version {selected.template_version_id||meta.template_version_id}</p>{selected.definition.items.map(item=>{const a=answers[item.id]||{status:'todo',note:'',evidence:[]};return <div key={item.id} className="border rounded p-3 space-y-2"><p className="text-xs font-semibold text-blue-700">{item.section}</p><p>{item.label}{item.required?' *':''}</p><p className="text-sm text-gray-500">{item.instructions}</p>{kind==='occurrences'&&<><Field label={`${item.label} status`}><select className="select" disabled={!isMine||!active} value={a.status} onChange={e=>setAnswers(prev=>({...prev,[item.id]:{...a,status:e.target.value}}))}><option value="todo">To do</option><option value="done">Done</option>{item.allow_na&&<option value="na">Not applicable</option>}</select></Field><Field label={`${item.label} note`}><textarea className="input" disabled={!isMine||!active} value={a.note||''} onChange={e=>setAnswers(prev=>({...prev,[item.id]:{...a,note:e.target.value}}))}/></Field>{item.evidence==='file'&&<Field label={`${item.label} evidence`}><select multiple className="select" disabled={!isMine||!active} value={a.evidence||[]} onChange={e=>setAnswers(prev=>({...prev,[item.id]:{...a,evidence:Array.from(e.target.selectedOptions,o=>o.value)}}))}>{selected.files.filter(f=>!f.internal).map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></Field>}<p className="text-xs">Evidence: {item.evidence||'none'}{item.allow_na?' · Not applicable needs a reason':''}</p></>}</div>;})}</div>}
    <div className="space-y-2"><h3 className="font-semibold">Attachments</h3>{selected.files.map(file=><button key={file.id} className="block text-blue-700 underline text-sm break-all" onClick={()=>download(file)}>{file.name}{file.internal?' (internal)':''}</button>)}{active&&selected.access.edit&&<Field label="Attach evidence or supporting file"><input aria-label="Attach file" type="file" accept=".png,.jpg,.jpeg,.pdf,.txt" disabled={busy} onChange={e=>{upload(e.target.files[0]);e.target.value='';}}/><p className="text-xs">PNG, JPEG, PDF or text · maximum 5 MB · private access</p></Field>}</div>
    {kind==='tasks'&&active&&isMine&&<Field label="Completion evidence"><select multiple className="select" value={proof} onChange={e=>setProof(Array.from(e.target.selectedOptions,o=>o.value))}>{selected.files.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></Field>}
    {kind!=='templates'&&<Field label={kind==='tickets'?'Reply / resolution / reason':'Progress update / completion note / reason'}><textarea aria-label="Workflow note" className="input" value={note} onChange={e=>setNote(e.target.value)}/></Field>}
    {kind==='tickets'&&selected.access.internal&&<Check label="Internal note (hidden from requester)" value={internal} onChange={setInternal}/>}
    <div className="flex flex-wrap gap-2">
     {kind==='tasks'&&selected.access.edit&&isMine&&<>{['pending','blocked','rejected'].includes(selected.status)&&actionButton('Start work','start')}{['pending','in_progress','rejected'].includes(selected.status)&&actionButton('Report blocker','block')}{['in_progress','rejected'].includes(selected.status)&&actionButton(meta.review_required===false?'Complete work':'Submit for review','submit',{evidence:proof})}{active&&actionButton('Save progress update','comment')}</>}
     {kind==='occurrences'&&selected.access.edit&&isMine&&active&&<>{actionButton('Save progress','save',{answers})}{actionButton(selected.definition.review_required?'Submit for review':'Complete checklist','submit',{answers})}</>}
     {['tasks','occurrences'].includes(kind)&&selected.status==='submitted'&&selected.access.approve&&!isMine&&<>{actionButton('Approve completion','approve')}{actionButton('Return with reason','return')}</>}
     {kind==='tickets'&&selected.access.edit&&selected.status!=='closed'&&actionButton('Send reply','reply',{internal})}
     {kind==='tickets'&&selected.access.internal&&<>{['open','assigned','waiting'].includes(selected.status)&&actionButton('Start work','start')}{['assigned','in_progress'].includes(selected.status)&&actionButton('Request information','wait')}{['assigned','in_progress','waiting'].includes(selected.status)&&actionButton('Resolve ticket','resolve')}</>}
     {kind==='tickets'&&selected.status==='resolved'&&(selected.user_id===user.id||selected.access.approve)&&actionButton('Close ticket','close')}
     {kind==='tickets'&&['resolved','closed'].includes(selected.status)&&(selected.user_id===user.id||selected.access.approve)&&actionButton('Reopen ticket','reopen')}
     {can('help_tickets','create')&&((kind==='tasks'&&selected.status==='blocked')||(kind==='occurrences'&&active))&&<button className="btn btn-secondary" onClick={()=>fresh('tickets',selected)}>Raise linked ticket</button>}
    </div>
    {((kind==='tasks'&&selected.access.manage&&active)||(kind==='tickets'&&selected.access.approve&&!['resolved','closed'].includes(selected.status)))&&<div className="border-t pt-3 space-y-2">{!selected.branch_id&&<Field label="Branch for earlier record"><select required className="select" value={assignBranch} onChange={e=>setAssignBranch(e.target.value)}><option value="">Select branch</option>{options?.branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></Field>}{kind==='tasks'&&(meta.review_required??true)&&<Field label="Reviewer"><select className="select" value={reviewer} onChange={e=>setReviewer(e.target.value)}>{uoptions}</select></Field>}<Field label="Accountable assignee"><select className="select" value={assignment} onChange={e=>setAssignment(e.target.value)}>{uoptions}</select></Field>{kind==='tasks'&&<Field label="New deadline (your device timezone)"><input type="datetime-local" className="input" value={deadline} onChange={e=>setDeadline(e.target.value)}/></Field>}{actionButton(kind==='tasks'?'Save reassignment / deadline':'Assign ticket',kind==='tasks'?'update':'assign',{assigned_to:Number(assignment),branch_id:Number(assignBranch)||undefined,reviewer_id:Number(reviewer)||undefined,...(kind==='tasks'&&deadline?{due_at:new Date(deadline).toISOString()}: {})})}</div>}
    {kind==='tasks'&&isMine&&active&&<div className="space-y-2"><Field label="Requested deadline (your device timezone)"><input className="input" type="datetime-local" value={deadline} onChange={e=>setDeadline(e.target.value)}/></Field>{actionButton('Request extension','request_extension',deadline?{due_at:new Date(deadline).toISOString()}:{},!deadline)}</div>}
    {kind==='tasks'&&meta.extension?.status==='pending'&&<div><p>Extension requested: {prettyDate(meta.extension.due_at)} — {meta.extension.reason}</p>{selected.access.approve&&!isMine&&<div className="flex gap-2">{actionButton('Approve extension','approve_extension')}{actionButton('Decline extension','reject_extension')}</div>}</div>}
    {kind==='templates'&&selected.access.manage&&selected.access.edit&&<div className="flex gap-2 flex-wrap"><button className="btn btn-primary" onClick={()=>{const fallback={title:selected.title,instructions:selected.description||'',items:[blankItem()],assignees:selected.assigned_to?[selected.assigned_to]:[],schedule:{frequency:'daily',start:day(),due_time:'18:00',timezone:'Asia/Kolkata',missed:'catch_up'}};setForm({kind:'templates',id:selected.id,version:selected.work_version,branch_id:selected.branch_id||options?.own_branch||'',definition:{...(selected.definition||fallback),effective_from:day()}});}}>Publish revised template</button>{meta.state==='active'&&actionButton('Pause template','pause')}{meta.state==='paused'&&actionButton('Resume template','resume')}{meta.state&&meta.state!=='retired'&&actionButton('Retire template','retire')}</div>}
    {kind==='templates'&&<div className="space-y-2"><button type="button" className="btn btn-secondary" onClick={async()=>{try{const {data:r}=await api.get('/work/templates/'+selected.id+'/legacy-history',{params:{page:legacy?legacy.page+1:1}});setLegacy(r);}catch(e){toast.error(e.response?.data?.error||'Could not load earlier submissions');}}}>{legacy?'Next page of earlier submissions':'View earlier submissions'}</button>{legacy&&<><p className="text-sm">Earlier submissions ? page {legacy.page}</p>{!legacy.rows.length&&<p>No earlier submissions on this page.</p>}{legacy.rows.map(r=><p key={r.id} className="border-b py-2 text-sm">{r.completion_date} ? {r.approval_status||'Earlier submission'} ? {r.notes||'No written note'}</p>)}</>}</div>}
    <details><summary className="cursor-pointer font-semibold">Activity history ({selected.events.length} most recent)</summary><div className="space-y-3 mt-2">{selected.events.map(e=><div key={e.id} className="border-b pb-2 text-sm"><p>{prettyDate(e.created_at)} · {e.actor_name||'Scheduled job'} · {e.action.replaceAll('_',' ')}{e.internal?' · Internal':''}</p>{e.detail.note&&<p className="whitespace-pre-wrap">{e.detail.note}</p>}{e.detail.before&&<p>Assignee {e.detail.before.assignee} → {e.detail.after.assignee}; deadline {prettyDate(e.detail.before.due_at)} → {prettyDate(e.detail.after.due_at)}</p>}{e.detail.ticket_id&&<Link className="text-blue-700" to={`/help-tickets?record=${e.detail.ticket_id}`}>Ticket #{e.detail.ticket_id}</Link>}</div>)}</div></details>
   </fieldset>}
  </Modal>

  <Modal isOpen={!!form} onClose={()=>setForm(null)} title={form?.kind==='templates'?'Checklist template':form?.kind==='tickets'?'Raise help ticket':'Assign task'} wide>
   {form&&<form className="space-y-4" onSubmit={saveForm}>
    <Field label="Branch"><select required className="select" value={form.branch_id} onChange={e=>update('branch_id',e.target.value)}><option value="">Select branch</option>{options?.branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></Field>
    {form.kind!=='templates'&&<><Field label="Title"><input required className="input" value={form.title} onChange={e=>update('title',e.target.value)}/></Field><Field label="Instructions / description"><textarea required className="input" value={form.description} onChange={e=>update('description',e.target.value)}/></Field><Field label="Priority"><select className="select" value={form.priority} onChange={e=>update('priority',e.target.value)}>{options?.priorities.filter(p=>p.active).map(p=><option value={p.id} key={p.id}>{p.label}</option>)}</select></Field></>}
    {form.kind==='tickets'&&<Field label="Category"><select className="select" value={form.category} onChange={e=>update('category',e.target.value)}>{options?.categories.filter(c=>c.active).map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select><p className="text-xs">The configured category route assigns support. Replies remain in the ticket.</p></Field>}
    {form.kind==='tasks'&&<><Field label="Accountable employee"><select required className="select" value={form.assigned_to} onChange={e=>update('assigned_to',e.target.value)}>{uoptions}</select></Field><Field label="Deadline (your device timezone)"><input required type="datetime-local" className="input" value={form.due_at} onChange={e=>update('due_at',e.target.value)}/></Field><Check label="Completion needs review" value={form.review_required} onChange={v=>update('review_required',v)}/><Check label="Completion requires a file" value={form.evidence_required} onChange={v=>update('evidence_required',v)}/>{form.review_required&&<Field label="Reviewer"><select required className="select" value={form.reviewer_id} onChange={e=>update('reviewer_id',e.target.value)}>{uoptions}</select></Field>}<Field label="Optional collaborators"><select multiple className="select" value={form.collaborators.map(String)} onChange={e=>update('collaborators',Array.from(e.target.selectedOptions,o=>Number(o.value)))}>{choiceUsers.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></Field></>}
    {form.kind==='templates'&&<>
     <div className="flex gap-2 flex-wrap"><span className="text-sm">Editable samples:</span>{['Opening preparation','Hygiene checks','Closing checks'].map((sample,i)=><button type="button" className="text-sm underline text-blue-700" key={sample} onClick={()=>{dupdate('title',sample);dupdate('items',[{...blankItem(),section:sample,label:['Prepare stations and reception','Clean and disinfect equipment','Check equipment and secure the salon'][i],instructions:'Review and adapt this example to the salon procedure.'}]);}}>{sample}</button>)}</div>
     <Field label="Template title"><input required className="input" value={form.definition.title} onChange={e=>dupdate('title',e.target.value)}/></Field><Field label="Template instructions"><textarea className="input" value={form.definition.instructions} onChange={e=>dupdate('instructions',e.target.value)}/></Field>
     <Field label="Accountable employees (one occurrence each)"><select multiple className="select" value={form.definition.assignees.map(String)} onChange={e=>dupdate('assignees',Array.from(e.target.selectedOptions,o=>Number(o.value)))}>{choiceUsers.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></Field>
     <Field label="Also include a manager's direct team"><select className="select" value={form.definition.team_manager_id||''} onChange={e=>dupdate('team_manager_id',Number(e.target.value)||null)}><option value="">No additional team</option>{choiceUsers.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select><p className="text-xs">Team membership is captured when this version is published.</p></Field>
     <div className="grid sm:grid-cols-2 gap-3"><Field label="Frequency"><select className="select" value={form.definition.schedule.frequency} onChange={e=>supdate('frequency',e.target.value)}>{['daily','weekly','monthly','selected_days','once'].map(v=><option value={v} key={v}>{v.replaceAll('_',' ')}</option>)}</select></Field><Field label="Due time"><input required className="input" type="time" value={form.definition.schedule.due_time} onChange={e=>supdate('due_time',e.target.value)}/></Field><Field label="Timezone"><input required className="input" value={form.definition.schedule.timezone} onChange={e=>supdate('timezone',e.target.value)}/></Field><Field label="Version effective from"><input required className="input" type="date" value={form.definition.effective_from} onChange={e=>dupdate('effective_from',e.target.value)}/></Field><Field label="Schedule start"><input required className="input" type="date" value={form.definition.schedule.start} onChange={e=>supdate('start',e.target.value)}/></Field><Field label="Schedule end (optional)"><input className="input" type="date" value={form.definition.schedule.end||''} onChange={e=>supdate('end',e.target.value||null)}/></Field></div>
     {['weekly','selected_days'].includes(form.definition.schedule.frequency)&&<div className="flex flex-wrap gap-3">{['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'].map((label,i)=><Check key={i} label={label} value={(form.definition.schedule.days||[]).includes(i)} onChange={v=>supdate('days',v?[...(form.definition.schedule.days||[]),i]:(form.definition.schedule.days||[]).filter(n=>n!==i))}/>)}</div>}
     {form.definition.schedule.frequency==='monthly'&&<Field label="Day of month (clamped to last day of shorter months)"><input className="input" type="number" min="1" max="31" value={form.definition.schedule.month_day||1} onChange={e=>supdate('month_day',Number(e.target.value))}/></Field>}
     <Field label="When scheduled runs are missed"><select className="select" value={form.definition.schedule.missed} onChange={e=>supdate('missed',e.target.value)}><option value="catch_up">Create missed occurrences, retaining their original due dates</option><option value="skip">Skip missed days; generate today only</option></select></Field>
     <Check label="Review required" value={form.definition.review_required} onChange={v=>dupdate('review_required',v)}/>{form.definition.review_required&&<Field label="Reviewer"><select required className="select" value={form.definition.reviewer_id} onChange={e=>dupdate('reviewer_id',Number(e.target.value))}>{uoptions}</select></Field>}
     {form.definition.items.map((item,i)=><div key={item.id} className="border rounded p-3 space-y-2"><p className="font-semibold">Item {i+1}</p>{['section','label','instructions'].map(key=><Field key={key} label={key==='label'?'Item name':key==='section'?'Section':'Instructions'}><input required={key==='label'} className="input" value={item[key]||''} onChange={e=>dupdate('items',form.definition.items.map((v,n)=>n===i?{...v,[key]:e.target.value}:v))}/></Field>)}<div className="flex gap-3"><Check label="Required" value={item.required} onChange={v=>dupdate('items',form.definition.items.map((x,n)=>n===i?{...x,required:v}:x))}/><Check label="Allow not applicable with reason" value={item.allow_na} onChange={v=>dupdate('items',form.definition.items.map((x,n)=>n===i?{...x,allow_na:v}:x))}/></div><Field label="Evidence required"><select className="select" value={item.evidence} onChange={e=>dupdate('items',form.definition.items.map((v,n)=>n===i?{...v,evidence:e.target.value}:v))}><option value="none">None</option><option value="note">Written note</option><option value="file">Attached file</option></select></Field><button type="button" className="text-red-700 text-sm" onClick={()=>dupdate('items',form.definition.items.filter((_,n)=>n!==i))}>Remove item</button></div>)}
     <button type="button" className="btn btn-secondary" onClick={()=>dupdate('items',[...form.definition.items,blankItem()])}>Add item</button>
    </>}
    <div className="flex justify-end gap-3"><button type="button" className="btn btn-secondary" onClick={()=>setForm(null)}>Cancel</button><button disabled={busy} className="btn btn-primary">{busy?'Saving…':'Save'}</button></div>
   </form>}
  </Modal>
 </div>;
}
