const test=require('node:test'),assert=require('node:assert/strict'),fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'../..'),esbuild=require(path.join(root,'client/node_modules/esbuild'));
const m={exports:{}};vm.runInNewContext(esbuild.transformSync(fs.readFileSync(path.join(root,'supabase/functions/_shared/attendance-engine.ts'),'utf8'),{loader:'ts',format:'cjs'}).code,{module:m,exports:m.exports,Date});
const {evaluateDay,shiftPlan,validatePolicy,validateSegments}=m.exports;
const policy={grace_minutes:10,full_day_hours:8,half_day_hours:4,late_half_day_minutes:0,late_grace_count:0,late_per_minute_rate:0,lates_to_absent:0,ot_threshold_hours:9,ot_rate_multiplier:1,cl_per_month:1,sl_per_month:1,pl_per_month:1,missing_checkout:'review',half_day_leave:'combine',off_work:'normal',sandwich:'none',short_leave:'review',below_half_day:'absent',capture_exception:'review',location_scope:'branch',weekly_off_paid:true,allow_multiple_sessions:true};
const employee={id:1,user_id:1,status:'active',join_date:'2026-01-01'};
const date='2026-09-15',stamp=t=>date+'T'+t+':00+05:30',plan=shiftPlan(date,{shift_start:'11:00',shift_end:'19:00'});
const row=(a,b,n=1)=>({capture_session:n,punch_in_time:stamp(a),punch_out_time:b?stamp(b):null,review_state:'accepted'});
const day=extra=>evaluateDay({date,employee,policy,plan,today:'2026-09-17',...extra});
test('Shift-relative lateness honors grace and full-day hours',()=>{assert.equal(day({attendance:[row('11:10','19:10')]}).late_minutes,0);const d=day({attendance:[row('11:11','19:11')]});assert.equal(d.late_minutes,1);assert.equal(d.pay,1);});
test('Hours on threshold and fractional half-day leave combine without double counting',()=>{assert.equal(day({attendance:[row('11:00','15:00')]}).pay,.5);const d=day({attendance:[row('11:00','15:00')],leaves:[{leave_type:'half_day'}]});assert.equal(d.pay,1);assert.equal(d.paid_leave,.5);assert.equal(day({attendance:[row('11:00','19:00')],leaves:[{leave_type:'half_day'}]}).pay,1);});
test('Missing checkout never fabricates worked hours or payable attendance',()=>{const d=day({attendance:[row('11:00',null)]});assert.equal(d.pay,null);assert.equal(d.hours,0);assert.ok(d.exceptions.includes('MISSING_CHECK_OUT'));assert.equal(day({policy:{...policy,missing_checkout:'absent'},attendance:[row('11:00',null)]}).pay,0);});
test('Tuesday weekly off follows roster, with explicit work compensation choice',()=>{assert.equal(day({weeklyOff:true,plan:null}).pay,1);assert.equal(day({weeklyOff:true,attendance:[row('11:00','19:00')],policy:{...policy,off_work:'extra_day'}}).pay,2);const c=day({weeklyOff:true,attendance:[row('11:00','19:00')],policy:{...policy,off_work:'comp_off'}});assert.equal(c.pay,1);assert.equal(c.comp_off_credit,1);});
test('Overnight work belongs to originating work date',()=>{const p=shiftPlan(date,{shift_start:'22:00',shift_end:'06:00'});const d=day({plan:p,attendance:[{capture_session:1,punch_in_time:stamp('22:00'),punch_out_time:'2026-09-16T06:00:00+05:30'}]});assert.equal(d.hours,8);assert.equal(d.pay,1);assert.equal(d.late_minutes,0);});
test('Split sessions add work without charging the gap as work',()=>{const p=shiftPlan(date,{segments:[{start:'09:00',end:'13:00'},{start:'17:00',end:'21:00'}]});const d=day({plan:p,attendance:[row('09:00','13:00'),row('17:00','21:00',2)]});assert.equal(p.scheduled_minutes,480);assert.equal(d.hours,8);assert.equal(d.pay,1);});
test('Overlap and pending location evidence block payment',()=>{assert.equal(day({attendance:[row('11:00','18:00'),row('17:00','21:00',2)]}).pay,null);assert.equal(day({attendance:[{...row('11:00','19:00'),review_state:'pending'}]}).pay,null);});
test('Employment bounds exclude before joining and after leaving',()=>{assert.equal(day({employee:{...employee,join_date:'2026-09-16'}}).label,'outside_employment');assert.equal(day({employee:{...employee,employment_end_date:'2026-09-14'}}).pay,0);assert.equal(day({employee:{...employee,join_date:null}}).pay,null);});
test('Unknown policy blocks payment; approved correction is explicit and retains raw input',()=>{assert.equal(day({policy:null}).pay,null);const raw=row('11:00',null),d=day({attendance:[raw],correction:{id:4,proposed:{hours:8,pay_fraction:1,late_minutes:0}}});assert.equal(d.pay,1);assert.equal(d.correction_id,4);assert.equal(raw.punch_out_time,null);});
test('Invalid shifts and conflicting penalty rules fail validation',()=>{assert.throws(()=>validateSegments([{start:'11:00',end:'10:00',end_day:0}]));assert.throws(()=>validateSegments([{start:'09:00',end:'14:00'},{start:'13:00',end:'17:00'}]));assert.throws(()=>validatePolicy({...policy,lates_to_absent:3,late_per_minute_rate:5}));assert.throws(()=>validatePolicy({...policy,late_grace_count:1.5}));assert.equal(validatePolicy({...policy}).grace_minutes,10);});

test('Full work does not consume half-day leave allowance; weekly off is not charged as leave',()=>{const full=day({attendance:[row('11:00','19:00')],leaves:[{leave_type:'half_day'}]});assert.equal(full.pay,1);assert.equal(full.paid_leave,0);const off=day({weeklyOff:true,leaves:[{leave_type:'full_day'}]});assert.equal(off.pay,1);assert.equal(off.paid_leave,0);});

test('Split-shift lateness includes the later session and overlap does not inflate hours',()=>{const p=shiftPlan(date,{segments:[{start:'09:00',end:'13:00'},{start:'17:00',end:'21:00'}]});assert.equal(day({plan:p,attendance:[row('09:00','13:00'),row('17:15','21:15',2)]}).late_minutes,5);assert.equal(day({attendance:[row('11:00','18:00'),row('17:00','21:00',2)]}).hours,10);});
