// Shared attendance/payroll service against a transaction-isolated PostgreSQL schema.
// Entire schema and fixtures roll back, including the synthetic policy.
const assert=require('assert/strict'),fs=require('fs'),path=require('path'),{Client}=require('pg');
const root=path.resolve(__dirname,'../..'),esbuild=require(path.join(root,'client/node_modules/esbuild'));
const compiled=esbuild.buildSync({entryPoints:[path.join(root,'supabase/functions/_shared/attendance-operations.ts')],bundle:true,platform:'node',format:'cjs',write:false}).outputFiles[0].text;
const m={exports:{}};new Function('module','exports','require',compiled)(m,m.exports,require);
const {calculateAttendanceMonth,payrollFromAttendance}=m.exports;
const c=new Client({connectionString:'postgresql://postgres:postgres@127.0.0.1:54322/postgres'});
const results=[];async function test(name,fn){await fn();results.push(name);console.log('PASS',name);}
(async()=>{
 await c.connect();assert.equal((await c.query("SELECT value FROM app_settings WHERE key='local_environment'")).rows[0]?.value,'sotyn-headmasters-local');await c.query('BEGIN');
 const schema='attendance_test_'+Date.now();await c.query('CREATE SCHEMA '+schema);await c.query('SET LOCAL search_path TO '+schema+', public');
 for(const t of ['employees','attendance','leave_requests','employee_shifts','attendance_roster_entries','attendance_shift_templates','attendance_policy_versions','attendance_requests','attendance_periods','attendance_month_snapshots','payroll_runs','payroll_advances','payroll_attendance_adjustments'])await c.query(`CREATE TABLE ${schema}.${t} (LIKE public.${t} INCLUDING ALL)`);
 const query=async(sql,args)=>{let i=0;return c.query(sql.replace(/\?/g,()=>'$'+(++i)),args);};
 const db={all:async(sql,...args)=>(await query(sql,args)).rows,get:async(sql,...args)=>(await query(sql,args)).rows[0],run:async(sql,...args)=>{const r=await query(sql,args);return {changes:r.rowCount};}};
 // Match Edge's numeric values.
 require('pg').types.setTypeParser(20,Number);require('pg').types.setTypeParser(1700,Number);
 const rules={grace_minutes:10,full_day_hours:8,half_day_hours:4,late_half_day_minutes:0,late_grace_count:0,late_per_minute_rate:5,lates_to_absent:0,ot_threshold_hours:9,ot_rate_multiplier:1,cl_per_month:1,sl_per_month:1,pl_per_month:1,missing_checkout:'review',half_day_leave:'combine',off_work:'normal',sandwich:'none',short_leave:'review',below_half_day:'absent',capture_exception:'review',location_scope:'branch',weekly_off_paid:true,allow_multiple_sessions:true};
 await db.run("INSERT INTO attendance_policy_versions(id,effective_from,rules,reason) VALUES(1,'2026-01-01',?,'Synthetic rolled-back rule')",rules);
 await db.run("INSERT INTO employees(id,user_id,name,status,join_date,salary) VALUES(1,1,'Synthetic month','active','2026-08-01',31000)");
 const employee=await db.get('SELECT * FROM employees WHERE id=1');
 await db.run("INSERT INTO employee_shifts(employee_id,effective_from,shift_start,shift_end,week_off_day) VALUES(1,'2026-08-01','11:00','19:00',2)");
 await db.run("INSERT INTO attendance(user_id,employee_id,date,punch_in_time,punch_out_time,capture_session) VALUES(1,1,'2026-08-03','2026-08-03T11:11:00+05:30','2026-08-03T19:11:00+05:30',1),(1,1,'2026-08-05','2026-08-05T11:00:00+05:30','2026-08-05T15:00:00+05:30',1)");
 await db.run("INSERT INTO leave_requests(id,user_id,leave_type,from_date,to_date,days,status) VALUES(1,1,'half_day','2026-08-05','2026-08-05',0.5,'approved')");
 let report;
 await test('Monthly half-day leave is fractional and Tuesday offs replace Sunday assumptions',async()=>{report=await calculateAttendanceMonth(db,employee,'2026-08');assert.equal(report.ready,true);assert.equal(report.paid_days,6);assert.equal(report.paid_leaves,.5);assert.equal(report.weekly_off_days,4);assert.equal(report.breakdown.find(d=>d.date==='2026-08-02').label,'absent');assert.equal(report.breakdown.find(d=>d.date==='2026-08-04').label,'weekly_off');});
 await test('Payroll uses the same daily results and shift-relative late minutes',async()=>{const p=await payrollFromAttendance(db,{basic_pct:100},employee,'2026-08');assert.equal(p.paid_days,report.paid_days);assert.equal(p.late_penalty,5);assert.equal(p.net_pay,5995);assert.equal(p.breakdown.find(d=>d.date==='2026-08-03').late_minutes,1);});
 await test('Sandwich rule uses actual off day and both adjacent attendance dates',async()=>{await db.run("INSERT INTO attendance_policy_versions(id,effective_from,rules,reason) VALUES(2,'2026-08-01',?,'Synthetic sandwich')",{...rules,sandwich:'both_absent'});const r=await calculateAttendanceMonth(db,employee,'2026-08');assert.equal(r.paid_days,3);assert.equal(r.breakdown.find(d=>d.date==='2026-08-11').label,'weekly_off_sandwich');assert.equal(r.breakdown.find(d=>d.date==='2026-08-04').pay,1);});
 await test('Leave amendments retain original leave and change evaluated result only after approval',async()=>{await db.run("INSERT INTO attendance_requests(request_id,payload_hash,employee_id,work_date,kind,proposed,reason,requested_by,status) VALUES('synthetic-amendment','hash',1,'2026-08-05','leave_amendment',?,'Synthetic cancellation',1,'pending')",{leave_id:1,action:'cancel',original_from:'2026-08-05',original_to:'2026-08-05'});assert.equal((await calculateAttendanceMonth(db,employee,'2026-08')).ready,false);await db.run("UPDATE attendance_requests SET status='approved' WHERE request_id='synthetic-amendment'");const r=await calculateAttendanceMonth(db,employee,'2026-08');assert.equal(r.paid_leaves,0);assert.equal(r.breakdown.find(d=>d.date==='2026-08-05').pay,.5);assert.equal((await db.get('SELECT status FROM leave_requests WHERE id=1')).status,'approved');});
 await test('Closed attendance returns saved revision instead of recalculating historical inputs',async()=>{await db.run("INSERT INTO attendance_month_snapshots(month,revision,employee_id,payload) VALUES('2026-08',1,1,?)",report);await db.run("INSERT INTO attendance_periods(month,state,revision) VALUES('2026-08','closed',1)");const r=await calculateAttendanceMonth(db,employee,'2026-08');assert.equal(r.locked,true);assert.equal(r.paid_days,6);assert.equal(r.paid_leaves,.5);});
 await test('Saved paid payroll survives employee and policy changes',async()=>{await db.run("INSERT INTO payroll_runs(month,employee_id,employee_name,base_salary,paid,status,snapshot_json) VALUES('2026-08',1,'Synthetic month',31000,1,'disbursed',?)",{employee_id:1,net_pay:5995,paid_days:6,breakdown:report.breakdown});const p=await payrollFromAttendance(db,{basic_pct:0},{...employee,salary:99999},'2026-08');assert.equal(p.net_pay,5995);assert.equal(p.paid,1);assert.equal(p.locked,true);});
 await test('Approved later adjustment appears only in target payroll',async()=>{await db.run("INSERT INTO payroll_attendance_adjustments(employee_id,source_month,source_revision,target_month,amount,reason,created_by,status,decided_by) VALUES(1,'2026-08',2,'2026-09',150,'Synthetic difference',1,'approved',2)");const p=await payrollFromAttendance(db,{basic_pct:100},employee,'2026-09');assert.equal(p.attendance_adjustment,150);assert.equal((await payrollFromAttendance(db,{},employee,'2026-08')).net_pay,5995);});
 fs.writeFileSync(path.join(root,'.local/attendance-monthly-results.json'),JSON.stringify({passed:results.length,results,at:new Date().toISOString(),transactionRolledBack:true},null,2));
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{await c.query('ROLLBACK').catch(()=>{});await c.end();});
