const fs = require('fs');
const path = require('path');
const { spawnSync, spawn } = require('child_process');
const root = path.resolve(__dirname, '../..');
const workspace = path.join(root, '.local');
const localSupabase = path.join(workspace, 'supabase');
const cli = path.join(root, 'node_modules/supabase/dist/supabase.js');
const credentialsFile = path.join(workspace, 'test-login.json');

// Do not inherit production credentials or database/proxy overrides.
const env = { ...process.env };
for (const key of Object.keys(env)) {
  if (/^(SUPABASE_|VITE_|DATABASE_URL$|DB_POOL_URL$|API_PROXY_TARGET$|ERP_SQLITE_PATH$|PGHOST$|PGPORT$|PGDATABASE$|PGUSER$|PGPASSWORD$|DOCKER_HOST$|DOCKER_CONTEXT$)/.test(key)) delete env[key];
}
if (process.platform === 'win32') {
  const dockerBin = 'C:\\Program Files\\Docker\\Docker\\resources\\bin';
  env.PATH = dockerBin + path.delimiter + (env.PATH || env.Path || '');
}
env.SUPABASE_TELEMETRY_DISABLED = 'true';

function assertLoopback(value, name) {
  const url = new URL(value);
  if (!['localhost', '127.0.0.1', '[::1]'].includes(url.hostname)) {
    throw new Error(`${name} must be local. Refusing to use a remote service.`);
  }
  return value;
}

function supabase(args, capture = false) {
  if (fs.existsSync(path.join(localSupabase, '.temp/project-ref'))) {
    throw new Error('The local workspace is linked to a remote project. Refusing to continue.');
  }
  const result = spawnSync(process.execPath, [cli, ...args, '--workdir', workspace], {
    cwd: root, env, encoding: 'utf8', stdio: capture ? 'pipe' : 'inherit', maxBuffer: 12 * 1024 * 1024,
  });
  if (result.error) throw result.error;
  if (result.status !== 0) throw new Error(capture ? (result.stderr || result.stdout || 'Supabase command failed') : `Supabase ${args[0]} failed. Check Docker Desktop is running; see docs/LOCAL-DEVELOPMENT.md.`);
  return result.stdout;
}

function prepare() {
  fs.mkdirSync(localSupabase, { recursive: true });
  fs.copyFileSync(path.join(__dirname, 'config.toml'), path.join(localSupabase, 'config.toml'));
  const functions = path.join(localSupabase, 'functions');
  const source = path.join(root, 'supabase/functions');
  if (!fs.existsSync(functions)) fs.symlinkSync(source, functions, process.platform === 'win32' ? 'junction' : 'dir');
  if (fs.realpathSync(functions) !== fs.realpathSync(source)) throw new Error('Unexpected local functions directory; refusing to use it.');
  if (!fs.existsSync(credentialsFile)) {
    fs.writeFileSync(credentialsFile, JSON.stringify({ username: 'local-admin', password: 'LocalTest123!' }, null, 2));
  }
  if (!fs.existsSync(path.join(localSupabase, 'migrations/20260101000000_local_baseline.sql'))) {
    const { password } = JSON.parse(fs.readFileSync(credentialsFile, 'utf8'));
    require('./schema').generateSchema(localSupabase, password);
  }
  for (const name of fs.readdirSync(path.join(root, 'supabase/migrations'))) {
    if (name.endsWith('.sql')) fs.copyFileSync(path.join(root, 'supabase/migrations', name), path.join(localSupabase, 'migrations', name));
  }
  console.log('Local workspace prepared. No production credentials or records were used.');
}

function status() {
  const output = supabase(['status', '--output', 'json'], true);
  const values = JSON.parse(output.slice(output.indexOf('{'), output.lastIndexOf('}') + 1));
  assertLoopback(values.API_URL, 'API_URL');
  assertLoopback(values.DB_URL, 'DB_URL');
  if (!values.ANON_KEY || !values.SERVICE_ROLE_KEY) throw new Error('Local Supabase status did not include the required local keys.');
  return values;
}

function writeFrontendEnv(values) {
  fs.writeFileSync(path.join(root, 'client/.env.development.local'), [
    '# Generated by npm run local:start. Local services only.',
    'VITE_API_BASE=/api',
    `VITE_SUPABASE_URL=${values.API_URL}`,
    `VITE_SUPABASE_ANON_KEY=${values.ANON_KEY}`, '',
  ].join('\n'));
}

async function check() {
  const values = status();
  const { Client } = require('pg');
  const db = new Client({ connectionString: values.DB_URL, ssl: false, connectionTimeoutMillis: 10000 });
  try {
    await db.connect();
    const marker = await db.query("SELECT value FROM app_settings WHERE key='local_environment'");
    if (marker.rows[0]?.value !== 'sotyn-headmasters-local') throw new Error('Local database marker is missing.');
  } finally { await db.end(); }
  const base = `${values.API_URL}/functions/v1/api`;
  const login = JSON.parse(fs.readFileSync(credentialsFile, 'utf8'));
  const request = async (route, options = {}) => {
    const response = await fetch(base + route, { ...options, signal: AbortSignal.timeout(60000) });
    const data = await response.json();
    if (!response.ok) throw new Error(`${route}: HTTP ${response.status}: ${JSON.stringify(data)}`);
    return data;
  };
  await request('/salon/public/info');
  const session = await request('/auth/login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(login) });
  const headers = { Authorization: `Bearer ${session.token}` };
  const user = await request('/auth/me', { headers });
  if (user.username !== login.username) throw new Error('Unexpected test account.');
  for (const route of ['/salon/services', '/salon/clients', '/salon/stylists', '/salon/commissions/dashboard/stats']) await request(route, { headers });
  const jsonHeaders = { ...headers, 'Content-Type': 'application/json' };
  const created = await request('/salon/clients', { method: 'POST', headers: jsonHeaders, body: JSON.stringify({ name: 'Local setup verification' }) });
  if (!created.id) throw new Error('Local client creation returned no ID.');
  try {
    await request(`/salon/clients/${created.id}`, { method: 'PUT', headers: jsonHeaders, body: JSON.stringify({ name: 'Local setup verified' }) });
    const saved = await request(`/salon/clients/${created.id}`, { headers });
    if (saved.name !== 'Local setup verified') throw new Error('Local update was not saved.');
  } finally { await request(`/salon/clients/${created.id}`, { method: 'DELETE', headers }); }
  console.log('PASS: local API, test login, session, salon endpoints and client create/update/delete.');
}

async function main() {
  const command = process.argv[2] || 'start';
  if (command === 'prepare') return prepare();
  if (command === 'stop') return supabase(['stop']);
  if (command === 'check') return check();
  if (command === 'status') {
    const values = status();
    console.log(`Local API: ${values.API_URL}\nLocal Studio: http://127.0.0.1:54323`);
    return;
  }
  if (command === 'start') {
    prepare();
    const docker = spawnSync('docker', ['info', '--format', '{{.OSType}}'], { env, encoding: 'utf8', timeout: 30000 });
    if (docker.status !== 0 || docker.stdout.trim() !== 'linux') throw new Error('Start Docker Desktop with its WSL 2/Linux engine first. A Windows restart may be required after installation.');
    supabase(['start']);
    supabase(['migration', 'up', '--local']);
    writeFrontendEnv(status());
    await check();
    console.log('Local backend ready. Start the frontend with npm run dev.');
    return;
  }
  if (command === 'frontend') {
    const values = status();
    writeFrontendEnv(values);
    env.API_PROXY_TARGET = values.API_URL + '/functions/v1/api';
    env.NODE_ENV = 'development';
    const child = spawn(process.execPath, [path.join(root, 'client/node_modules/vite/bin/vite.js'), '--mode', 'development'], {
      cwd: path.join(root, 'client'), env, stdio: 'inherit',
    });
    child.on('exit', (code) => { process.exitCode = code || 0; });
    child.on('error', (error) => { console.error(error.message); process.exitCode = 1; });
    return;
  }
  throw new Error(`Unknown local command: ${command}`);
}
main().catch((error) => { console.error(error.message); process.exitCode = 1; });
