// Generate a fresh LOCAL baseline from the checked-in schema, never a live DB.
const fs = require('fs');
const path = require('path');
const bcrypt = require('bcryptjs');

const q = (name) => '"' + name.replace(/"/g, '""') + '"';
const literal = (value) => value == null ? 'NULL' : typeof value === 'number'
  ? String(value) : "'" + String(value).replace(/'/g, "''") + "'";
const pgType = (type) => /INT|BOOL/i.test(type) ? 'bigint'
  : /REAL|FLOA|DOUB|NUMERIC|DECIMAL/i.test(type) ? 'double precision'
    : /BLOB/i.test(type) ? 'bytea' : 'text';

function generateSchema(destination, password) {
  // A new in-memory database avoids reading data/erp.db or any .env credentials.
  process.env.ERP_SQLITE_PATH = ':memory:';
  process.env.ERP_DISABLE_DEMO_SEED = '1';
  const db = require('../../server/db/schema').initializeDatabase();
  const tables = db.prepare("SELECT name, sql FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name").all();
  const ddl = ['-- Generated for isolated local development only. Do not deploy this baseline.'];
  const foreignKeys = [];
  const indexes = [];
  for (const { name, sql } of tables) {
    const columns = db.prepare(`PRAGMA table_info(${q(name)})`).all();
    const pk = columns.filter((c) => c.pk).sort((a, b) => a.pk - b.pk);
    const identity = pk.length === 1 && /INT/i.test(pk[0].type);
    const definitions = columns.map((c) => {
      const type = pgType(c.type);
      let def = c.dflt_value;
      if (def && /CURRENT_TIMESTAMP|datetime\s*\(\s*'now'/i.test(def)) def = "to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI:SS')";
      else if (def && /^CURRENT_DATE$/i.test(def)) def = "to_char(now() at time zone 'utc', 'YYYY-MM-DD')";
      else if (def && /^CURRENT_TIME$/i.test(def)) def = "to_char(now() at time zone 'utc', 'HH24:MI:SS')";
      else if (type === 'text' && def && /^-?\d+(\.\d+)?$/.test(def)) def = literal(def);
      if (identity && c.pk) return `${q(c.name)} ${type} GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY`;
      return `${q(c.name)} ${type}${c.notnull ? ' NOT NULL' : ''}${def != null ? ' DEFAULT ' + def : ''}`;
    });
    if (!identity && pk.length) definitions.push(`PRIMARY KEY (${pk.map((c) => q(c.name)).join(', ')})`);
    // Preserve the enum CHECKs used by the application (no nested expressions).
    for (const match of sql.matchAll(/CHECK\s*\(\s*(\w+)\s+IN\s*\(([^)]+)\)\s*\)/gi)) {
      definitions.push(`CHECK (${q(match[1])} IN (${match[2]}))`);
    }
    ddl.push(`CREATE TABLE public.${q(name)} (\n  ${definitions.join(',\n  ')}\n);`);
    // Disable Data API access; the backend uses its private DB connection.
    ddl.push(`ALTER TABLE public.${q(name)} ENABLE ROW LEVEL SECURITY;`);
    const fkGroups = new Map();
    for (const fk of db.prepare(`PRAGMA foreign_key_list(${q(name)})`).all()) {
      if (!fkGroups.has(fk.id)) fkGroups.set(fk.id, []);
      fkGroups.get(fk.id).push(fk);
    }
    for (const group of fkGroups.values()) {
      group.sort((a, b) => a.seq - b.seq);
      const fk = group[0];
      if (!tables.some((table) => table.name === fk.table)) {
        ddl.push(`-- Legacy FK ${name}.${fk.from} references missing table ${fk.table}; omitted locally.`);
        continue;
      }
      const target = group.every((f) => f.to) ? ` (${group.map((f) => q(f.to)).join(', ')})` : '';
      foreignKeys.push(`ALTER TABLE public.${q(name)} ADD FOREIGN KEY (${group.map((f) => q(f.from)).join(', ')}) REFERENCES public.${q(fk.table)}${target} ON DELETE ${fk.on_delete} ON UPDATE ${fk.on_update};`);
    }
    for (const idx of db.prepare(`PRAGMA index_list(${q(name)})`).all()) {
      if (idx.origin === 'pk') continue;
      const cols = db.prepare(`PRAGMA index_info(${q(idx.name)})`).all();
      if (!cols.length || cols.some((c) => c.name == null)) continue;
      const indexName = idx.name.startsWith('sqlite_') ? `local_uq_${name}_${idx.seq}` : idx.name;
      let predicate = '';
      if (idx.partial) {
        const source = db.prepare('SELECT sql FROM sqlite_master WHERE name=?').get(idx.name)?.sql || '';
        predicate = source.match(/\bWHERE\b[\s\S]*$/i)?.[0] || '';
      }
      indexes.push(`CREATE ${idx.unique ? 'UNIQUE ' : ''}INDEX ${q(indexName)} ON public.${q(name)} (${cols.map((c) => q(c.name)).join(', ')}) ${predicate};`);
    }
  }
  ddl.push(...indexes, ...foreignKeys);
  ddl.push('ALTER TABLE public.users ADD COLUMN IF NOT EXISTS auth_user_id uuid UNIQUE;');
  // Chat has its own historical schema, separate from the ERP SQLite schema.
  const chatSource = fs.readFileSync(path.join(__dirname, '../migrate-chat-to-supabase.js'), 'utf8');
  const chatDdl = chatSource.match(/const DDL = `([\s\S]*?)`;/)?.[1];
  if (!chatDdl) throw new Error('Could not read the checked-in chat schema.');
  ddl.push(chatDdl);
  for (const table of ['chat_groups', 'chat_group_members', 'chat_messages', 'chat_reads']) {
    ddl.push(`ALTER TABLE public.${table} ENABLE ROW LEVEL SECURITY;`);
  }
  fs.mkdirSync(path.join(destination, 'migrations'), { recursive: true });
  fs.writeFileSync(path.join(destination, 'migrations/20260101000000_local_baseline.sql'), ddl.join('\n\n'));

  const seed = ['-- Synthetic local fixtures only. Never run against production.'];
  // Reuse only generic role definitions from the fresh in-memory bootstrap.
  for (const table of ['roles', 'role_permissions']) {
    for (const row of db.prepare(`SELECT * FROM ${q(table)}`).all()) {
      seed.push(`INSERT INTO public.${q(table)} (${Object.keys(row).map(q).join(', ')}) VALUES (${Object.values(row).map(literal).join(', ')});`);
    }
    seed.push(`SELECT setval(pg_get_serial_sequence('public.${table}', 'id'), COALESCE((SELECT MAX(id) FROM public.${q(table)}), 0) + 1, false);`);
  }
  seed.push(`INSERT INTO users (name,email,username,password,role,department) VALUES ('Local Test Admin','local-admin@example.test','local-admin',${literal(bcrypt.hashSync(password, 10))},'admin','Management');`);
  seed.push("INSERT INTO user_roles (user_id,role_id) SELECT u.id,r.id FROM users u CROSS JOIN roles r WHERE u.username='local-admin' AND r.name='Admin';");
  seed.push("INSERT INTO salon_settings (id,salon_name) VALUES (1,'LOCAL TEST SALON');");
  seed.push("INSERT INTO app_settings (key,value) VALUES ('local_environment','sotyn-headmasters-local');");
  seed.push("INSERT INTO service_categories (name,sort_order) VALUES ('Test Hair Services',1);");
  seed.push("INSERT INTO services (category_id,name,code,duration_min,price) SELECT id,'Test Haircut','TEST-001',30,500 FROM service_categories WHERE name='Test Hair Services';");
  seed.push("INSERT INTO stylists (name,specialization,commission_pct) VALUES ('Test Stylist','Hair',10);");
  seed.push("INSERT INTO salon_clients (name,client_code,email,notes) VALUES ('Test Client','LOCAL-001','client@example.test','Synthetic local test record');");
  seed.push("INSERT INTO storage.buckets (id,name,public) VALUES ('uploads','uploads',true) ON CONFLICT (id) DO NOTHING;");
  fs.writeFileSync(path.join(destination, 'seed.sql'), seed.join('\n'));
  db.close();
  console.log(`Generated ${tables.length} local tables and synthetic test fixtures.`);
}

module.exports = { generateSchema };
