-- ==========================================
-- SOTYN.HEADMASTERS PRODUCTION MIGRATIONS BUNDLE
-- Non-destructive additive schema updates (8 migrations from Sep 17-18)
-- ==========================================

-- ------------------------------------------
-- Pre-step: Register verified production admin IDs (1: Admin, 39: Gaekwad Ravi Shankar Rao)
-- ------------------------------------------
CREATE TABLE IF NOT EXISTS attendance_permission_managers (
  user_id bigint PRIMARY KEY REFERENCES users(id), 
  granted_at timestamptz NOT NULL DEFAULT now()
);
INSERT INTO attendance_permission_managers (user_id) VALUES (1), (39) ON CONFLICT DO NOTHING;

-- ------------------------------------------
-- Migration: 20260917000100_attendance_foundation.sql
-- ------------------------------------------
DO $$
DECLARE owner_id bigint;
BEGIN
  owner_id := nullif(current_setting('attendance.bootstrap_user_id', true), '')::bigint;
  IF owner_id IS NULL AND EXISTS (SELECT 1 FROM app_settings WHERE key='local_environment' AND value='sotyn-headmasters-local') THEN
    SELECT id INTO owner_id FROM users WHERE username='local-admin' AND active=1;
  END IF;
  IF owner_id IS NOT NULL THEN
    IF NOT EXISTS (SELECT 1 FROM users WHERE id=owner_id AND active=1 AND COALESCE(archived,0)=0) THEN
      RAISE EXCEPTION 'Bootstrap owner must be an existing active, nonarchived login';
    END IF;
    INSERT INTO attendance_permission_managers(user_id) VALUES(owner_id) ON CONFLICT DO NOTHING;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM attendance_permission_managers) THEN
    RAISE EXCEPTION 'Nominate and verify a permission owner with attendance.bootstrap_user_id before this migration';
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS attendance_branches (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL UNIQUE, name text NOT NULL, active integer NOT NULL DEFAULT 1 CHECK(active IN (0,1))
);
ALTER TABLE employees ADD COLUMN IF NOT EXISTS attendance_branch_id bigint REFERENCES attendance_branches(id);
ALTER TABLE geofence_settings ADD COLUMN IF NOT EXISTS attendance_branch_id bigint REFERENCES attendance_branches(id);
ALTER TABLE role_permissions ADD COLUMN IF NOT EXISTS scope_mode text NOT NULL DEFAULT 'self' CHECK(scope_mode IN ('self','team','branch','all'));
ALTER TABLE role_permissions ADD COLUMN IF NOT EXISTS scope_branches text NOT NULL DEFAULT '[]';
UPDATE role_permissions SET scope_mode='all' WHERE can_see_all=1;

-- Keep existing action grants. New actions inherit only their explicitly stored predecessor grants.
INSERT INTO role_permissions(role_id,module,can_view,can_create,can_edit,can_delete,can_approve,can_see_all,scope_mode,scope_branches)
SELECT p.role_id,m.target,p.can_view,p.can_create,p.can_edit,p.can_delete,p.can_approve,p.can_see_all,p.scope_mode,p.scope_branches
FROM role_permissions p JOIN (VALUES
 ('attendance','attendance_capture'), ('attendance','attendance_corrections'),
 ('attendance','attendance_locations'), ('attendance','attendance_tracking'),
 ('employees','employee_shifts'), ('employees','employee_links'), ('payroll','attendance_rules')
) AS m(source,target) ON p.module=m.source
ON CONFLICT(role_id,module) DO NOTHING;

INSERT INTO roles(name,description,is_system) VALUES('Attendance foundation owner','Explicit, revocable attendance grants for the nominated permission owner',1) ON CONFLICT(name) DO NOTHING;
INSERT INTO role_permissions(role_id,module,can_view,can_create,can_edit,can_delete,can_approve,can_see_all,scope_mode)
SELECT r.id,m.module,1,1,1,1,1,1,'all' FROM roles r CROSS JOIN (VALUES
 ('attendance'),('employees'),('payroll'),('attendance_capture'),('attendance_corrections'),
 ('attendance_locations'),('attendance_tracking'),('employee_shifts'),('employee_links'),('attendance_rules')
) AS m(module) WHERE r.name='Attendance foundation owner' ON CONFLICT(role_id,module) DO NOTHING;
INSERT INTO user_roles(user_id,role_id)
SELECT o.user_id,r.id FROM attendance_permission_managers o CROSS JOIN roles r WHERE r.name='Attendance foundation owner'
ON CONFLICT(user_id,role_id) DO NOTHING;

-- Widen only integer columns. Do not presume a hosted decimal column is defective.
DO $$ BEGIN
 IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='leave_requests' AND column_name='days' AND data_type IN ('smallint','integer','bigint')) THEN
   ALTER TABLE leave_requests ALTER COLUMN days TYPE numeric USING days::numeric;
 END IF;
END $$;
INSERT INTO payroll_settings(id) VALUES(1) ON CONFLICT(id) DO NOTHING;

-- Keep every original attendance row. Legacy rows are intentionally outside new-session uniqueness.
ALTER TABLE attendance ADD COLUMN IF NOT EXISTS capture_session integer;
ALTER TABLE attendance ADD COLUMN IF NOT EXISTS capture_state text;
CREATE UNIQUE INDEX IF NOT EXISTS attendance_session_identity ON attendance(user_id,date,capture_session) WHERE capture_session IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS attendance_one_open_session ON attendance(user_id) WHERE capture_state='open';
CREATE TABLE IF NOT EXISTS attendance_capture_events (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id bigint NOT NULL REFERENCES users(id), request_id text NOT NULL,
 attendance_id bigint NOT NULL REFERENCES attendance(id), kind text NOT NULL CHECK(kind IN ('in','out')),
 captured_at timestamptz NOT NULL, received_at timestamptz NOT NULL DEFAULT now(),
 payload_hash text NOT NULL, evidence jsonb NOT NULL,
 UNIQUE(user_id,request_id), UNIQUE(attendance_id,kind)
);
-- No automatic cleanup/guessing; this view is the migration/linkage review queue.
CREATE OR REPLACE VIEW attendance_foundation_conflicts AS
 SELECT 'duplicate_attendance_day'::text AS kind, user_id::text AS subject, date::text AS detail, count(*) AS records
 FROM attendance WHERE user_id IS NOT NULL GROUP BY user_id,date HAVING count(*)>1
 UNION ALL SELECT 'ambiguous_employee_login',user_id::text,''::text,count(*) FROM employees WHERE user_id IS NOT NULL GROUP BY user_id HAVING count(*)>1
 UNION ALL SELECT 'unlinked_employee',id::text,name::text,1::bigint FROM employees WHERE user_id IS NULL;

CREATE INDEX IF NOT EXISTS employee_attendance_branch ON employees(attendance_branch_id,user_id);
CREATE INDEX IF NOT EXISTS employee_attendance_managers ON employees(reporting_manager_id_1,reporting_manager_id_2);
ALTER TABLE attendance_permission_managers ENABLE ROW LEVEL SECURITY;
ALTER TABLE attendance_branches ENABLE ROW LEVEL SECURITY;
ALTER TABLE attendance_capture_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON attendance_foundation_conflicts FROM anon, authenticated;


-- ------------------------------------------
-- Migration: 20260917000200_attendance_self_service.sql
-- ------------------------------------------
-- Basic employee self-service, explicitly requested by the owner.
-- Initial assignment only: later owner revocations are not restored by login/GET.
INSERT INTO roles(name,description,is_system)
VALUES('Employee attendance self-service','Own attendance history and punch in/out only; broader access requires separate grants',1)
ON CONFLICT(name) DO NOTHING;
INSERT INTO role_permissions(role_id,module,can_view,can_create,can_edit,can_delete,can_approve,can_see_all,scope_mode,scope_branches)
SELECT r.id,m.module,1,m.can_create,0,0,0,0,'self','[]'
FROM roles r CROSS JOIN (VALUES ('attendance',0),('attendance_capture',1)) m(module,can_create)
WHERE r.name='Employee attendance self-service'
ON CONFLICT(role_id,module) DO NOTHING;
INSERT INTO user_roles(user_id,role_id)
SELECT u.id,r.id FROM users u CROSS JOIN roles r
WHERE r.name='Employee attendance self-service' AND u.active=1 AND COALESCE(u.archived,0)=0
ON CONFLICT(user_id,role_id) DO NOTHING;


-- ------------------------------------------
-- Migration: 20260917000300_attendance_operations.sql
-- ------------------------------------------
-- Additive attendance operations. No historical attendance is deleted or recalculated.
ALTER TABLE employees ADD COLUMN IF NOT EXISTS employment_end_date text;
ALTER TABLE attendance ADD COLUMN IF NOT EXISTS employee_id bigint REFERENCES employees(id);
ALTER TABLE attendance ADD COLUMN IF NOT EXISTS shift_snapshot jsonb;
ALTER TABLE attendance ADD COLUMN IF NOT EXISTS policy_version_id bigint;
ALTER TABLE attendance ADD COLUMN IF NOT EXISTS review_state text NOT NULL DEFAULT 'accepted' CHECK(review_state IN ('accepted','pending','rejected'));
ALTER TABLE payroll_runs ADD COLUMN IF NOT EXISTS snapshot_json jsonb;
ALTER TABLE payroll_runs ADD COLUMN IF NOT EXISTS attendance_revision integer NOT NULL DEFAULT 1;

CREATE TABLE attendance_policy_versions (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 effective_from text NOT NULL CHECK(effective_from ~ '^\d{4}-\d{2}-\d{2}$'),
 rules jsonb NOT NULL, reason text NOT NULL, created_by bigint REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE attendance ADD CONSTRAINT attendance_policy_version_fk FOREIGN KEY(policy_version_id) REFERENCES attendance_policy_versions(id);
CREATE TABLE attendance_shift_templates (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, code text NOT NULL, version integer NOT NULL,
 name text NOT NULL, segments jsonb NOT NULL, week_off_days jsonb NOT NULL,
 created_by bigint REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(code,version)
);
CREATE TABLE attendance_roster_batches (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, request_id text NOT NULL UNIQUE,
 payload_hash text NOT NULL, created_by bigint REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(), row_count integer NOT NULL
);
CREATE TABLE attendance_roster_entries (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, employee_id bigint NOT NULL REFERENCES employees(id),
 work_date text NOT NULL, day_type text NOT NULL CHECK(day_type IN ('work','off')),
 template_id bigint REFERENCES attendance_shift_templates(id), reason text NOT NULL,
 batch_id bigint REFERENCES attendance_roster_batches(id), created_by bigint REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(),
 CHECK(day_type='off' OR template_id IS NOT NULL)
);
CREATE INDEX attendance_roster_lookup ON attendance_roster_entries(employee_id,work_date,id DESC);
CREATE TABLE attendance_requests (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, request_id text NOT NULL, payload_hash text NOT NULL,
 employee_id bigint NOT NULL REFERENCES employees(id), work_date text NOT NULL,
 kind text NOT NULL CHECK(kind IN ('correction','capture_exception')),
 proposed jsonb NOT NULL, reason text NOT NULL, requested_by bigint NOT NULL REFERENCES users(id),
 requested_at timestamptz NOT NULL DEFAULT now(), status text NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','approved','rejected')),
 decided_by bigint REFERENCES users(id), decided_at timestamptz, decision_reason text,
 UNIQUE(requested_by,request_id), CHECK(decided_by IS NULL OR decided_by<>requested_by)
);
CREATE INDEX attendance_requests_day ON attendance_requests(employee_id,work_date,id DESC);
CREATE TABLE attendance_periods (
 month text PRIMARY KEY CHECK(month ~ '^\d{4}-(0[1-9]|1[0-2])$'),
 state text NOT NULL CHECK(state IN ('open','closed')), revision integer NOT NULL DEFAULT 1,
 changed_by bigint REFERENCES users(id), changed_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE attendance_period_events (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, month text NOT NULL REFERENCES attendance_periods(month),
 revision integer NOT NULL, action text NOT NULL, reason text NOT NULL, actor_id bigint REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE attendance_month_snapshots (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, month text NOT NULL, revision integer NOT NULL,
 employee_id bigint NOT NULL REFERENCES employees(id), payload jsonb NOT NULL, created_by bigint REFERENCES users(id),
 created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(month,revision,employee_id)
);
CREATE TABLE payroll_snapshot_history (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, payroll_run_id bigint REFERENCES payroll_runs(id),
 month text NOT NULL, employee_id bigint REFERENCES employees(id), payload jsonb NOT NULL,
 provenance text NOT NULL, actor_id bigint REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE payroll_attendance_adjustments (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, employee_id bigint NOT NULL REFERENCES employees(id),
 source_month text NOT NULL, source_revision integer NOT NULL, target_month text NOT NULL,
 amount numeric NOT NULL, reason text NOT NULL, created_by bigint NOT NULL REFERENCES users(id),
 status text NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','approved','rejected')),
 decided_by bigint REFERENCES users(id), decided_at timestamptz,
 UNIQUE(employee_id,source_month,source_revision), CHECK(decided_by IS NULL OR decided_by<>created_by), CHECK(target_month>source_month)
);
-- Preserve existing payroll as it was stored. Do not fabricate missing historical inputs.
INSERT INTO payroll_snapshot_history(payroll_run_id,month,employee_id,payload,provenance)
SELECT id,month,employee_id,to_jsonb(p),'legacy snapshot; historical policy inputs may be unavailable' FROM payroll_runs p;
INSERT INTO attendance_periods(month,state)
SELECT DISTINCT month,'closed' FROM payroll_runs WHERE status IN ('finalised','disbursed') OR paid=1 ON CONFLICT DO NOTHING;

CREATE FUNCTION attendance_immutable() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN RAISE EXCEPTION 'Original evidence and published versions are immutable; create an amendment' USING ERRCODE='P0001'; END $$;
DO $$ DECLARE t text; BEGIN
 FOREACH t IN ARRAY ARRAY['attendance_capture_events','attendance_policy_versions','attendance_shift_templates','attendance_roster_entries','attendance_roster_batches','attendance_period_events','attendance_month_snapshots','payroll_snapshot_history'] LOOP
  EXECUTE format('CREATE TRIGGER immutable_record BEFORE UPDATE OR DELETE ON %I FOR EACH ROW EXECUTE FUNCTION attendance_immutable()',t);
 END LOOP;
END $$;

-- All attendance writers and period closure serialize on this lock. Checks are
-- repeated in the DB so an old client cannot race a period closure.
CREATE FUNCTION attendance_assert_open(d text) RETURNS void LANGUAGE plpgsql AS $$
BEGIN
 PERFORM pg_advisory_xact_lock(7430,1);
 IF EXISTS(SELECT 1 FROM attendance_periods WHERE month=left(d,7) AND state='closed') THEN
  RAISE EXCEPTION 'Attendance period % is closed; an authorized reopen is required',left(d,7) USING ERRCODE='P0001';
 END IF;
END $$;
CREATE FUNCTION attendance_period_guard() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE a jsonb; b jsonb; lo text; hi text; p record;
BEGIN
 PERFORM pg_advisory_xact_lock(7430,1);
 IF TG_OP<>'INSERT' THEN a:=to_jsonb(OLD); END IF;
 IF TG_OP<>'DELETE' THEN b:=to_jsonb(NEW); END IF;
 FOR p IN SELECT x FROM (VALUES(a),(b)) v(x) WHERE x IS NOT NULL LOOP
  IF TG_TABLE_NAME='attendance' THEN PERFORM attendance_assert_open(p.x->>'date');
  ELSIF TG_TABLE_NAME IN ('attendance_roster_entries','attendance_requests') THEN PERFORM attendance_assert_open(p.x->>'work_date');
  ELSIF TG_TABLE_NAME IN ('payroll_advances','payroll_attendance_adjustments') THEN PERFORM attendance_assert_open(COALESCE(p.x->>'target_month',p.x->>'month')||'-01');
  ELSIF TG_TABLE_NAME='leave_requests' THEN
   lo:=p.x->>'from_date'; hi:=COALESCE(p.x->>'to_date',lo);
   IF EXISTS(SELECT 1 FROM attendance_periods WHERE state='closed' AND month BETWEEN left(lo,7) AND left(hi,7)) THEN RAISE EXCEPTION 'Leave overlaps a closed attendance period' USING ERRCODE='P0001'; END IF;
  ELSE
   IF EXISTS(SELECT 1 FROM attendance_periods WHERE state='closed' AND month>=left(p.x->>'effective_from',7)) THEN RAISE EXCEPTION 'Effective date affects a closed attendance period' USING ERRCODE='P0001'; END IF;
  END IF;
 END LOOP;
 IF TG_OP='DELETE' THEN RETURN OLD; END IF; RETURN NEW;
END $$;
DO $$ DECLARE t text; BEGIN
 FOREACH t IN ARRAY ARRAY['attendance','leave_requests','employee_shifts','attendance_roster_entries','attendance_requests','attendance_policy_versions','payroll_advances','payroll_attendance_adjustments'] LOOP
  EXECUTE format('CREATE TRIGGER period_guard BEFORE INSERT OR UPDATE OR DELETE ON %I FOR EACH ROW EXECUTE FUNCTION attendance_period_guard()',t);
 END LOOP;
END $$;
CREATE FUNCTION attendance_decision_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF TG_OP='DELETE' OR OLD.status<>'pending' THEN RAISE EXCEPTION 'Decisions are preserved; submit a new amendment' USING ERRCODE='P0001'; END IF;
 IF NEW.proposed IS DISTINCT FROM OLD.proposed OR NEW.requested_by<>OLD.requested_by OR NEW.employee_id<>OLD.employee_id OR NEW.work_date<>OLD.work_date THEN RAISE EXCEPTION 'Original request must be preserved' USING ERRCODE='P0001'; END IF;
 RETURN NEW;
END $$;
CREATE TRIGGER decision_guard BEFORE UPDATE OR DELETE ON attendance_requests FOR EACH ROW EXECUTE FUNCTION attendance_decision_guard();
CREATE FUNCTION payroll_evidence_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 PERFORM pg_advisory_xact_lock(7430,1);
 IF TG_OP='DELETE' THEN RAISE EXCEPTION 'Payroll snapshots cannot be deleted' USING ERRCODE='P0001'; END IF;
 IF TG_OP='UPDATE' AND (OLD.paid=1 OR OLD.status='disbursed') AND NEW IS DISTINCT FROM OLD THEN RAISE EXCEPTION 'Paid payroll is immutable; use a later adjustment' USING ERRCODE='P0001'; END IF;
 IF TG_OP='UPDATE' AND OLD.status='finalised' AND
  (to_jsonb(NEW)-ARRAY['paid','paid_at','paid_by','status']) IS DISTINCT FROM (to_jsonb(OLD)-ARRAY['paid','paid_at','paid_by','status']) THEN
  RAISE EXCEPTION 'Finalised payroll inputs cannot be overwritten' USING ERRCODE='P0001';
 END IF;
 RETURN NEW;
END $$;
CREATE TRIGGER payroll_evidence_guard BEFORE UPDATE OR DELETE ON payroll_runs FOR EACH ROW EXECUTE FUNCTION payroll_evidence_guard();

INSERT INTO role_permissions(role_id,module,can_view,can_create,can_edit,can_delete,can_approve,can_see_all,scope_mode,scope_branches)
SELECT p.role_id,m.target,p.can_view,p.can_create,p.can_edit,p.can_delete,p.can_approve,p.can_see_all,p.scope_mode,p.scope_branches
FROM role_permissions p JOIN (VALUES('employee_shifts','attendance_rosters'),('attendance_rules','attendance_policies'),('attendance_corrections','attendance_requests'),('payroll','attendance_periods')) m(source,target) ON p.module=m.source
ON CONFLICT DO NOTHING;
INSERT INTO role_permissions(role_id,module,can_view,can_create,scope_mode)
SELECT id,'attendance_requests',1,1,'self' FROM roles WHERE name='Employee attendance self-service' ON CONFLICT DO NOTHING;
DO $$ DECLARE t text; BEGIN
 FOREACH t IN ARRAY ARRAY['attendance_policy_versions','attendance_shift_templates','attendance_roster_batches','attendance_roster_entries','attendance_requests','attendance_periods','attendance_period_events','attendance_month_snapshots','payroll_snapshot_history','payroll_attendance_adjustments'] LOOP
  EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY',t);
 END LOOP;
END $$;


-- ------------------------------------------
-- Migration: 20260917000400_attendance_evidence_guards.sql
-- ------------------------------------------
-- Preserve amendment decisions and original captures, including writes from old clients.
ALTER TABLE payroll_attendance_adjustments ADD COLUMN decision_reason text;
ALTER TABLE payroll_attendance_adjustments ADD COLUMN created_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE attendance_requests DROP CONSTRAINT attendance_requests_kind_check;
ALTER TABLE attendance_requests ADD CONSTRAINT attendance_requests_kind_check CHECK(kind IN ('correction','capture_exception','leave_amendment'));

CREATE OR REPLACE FUNCTION attendance_decision_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF TG_OP='DELETE' OR OLD.status<>'pending' THEN RAISE EXCEPTION 'Decisions are preserved; submit a new amendment' USING ERRCODE='P0001'; END IF;
 IF (to_jsonb(NEW)-ARRAY['status','decided_by','decided_at','decision_reason']) IS DISTINCT FROM (to_jsonb(OLD)-ARRAY['status','decided_by','decided_at','decision_reason']) THEN
  RAISE EXCEPTION 'Original request must be preserved' USING ERRCODE='P0001';
 END IF;
 IF NEW.status<>'pending' AND (NEW.decided_by IS NULL OR NEW.decided_at IS NULL OR length(trim(COALESCE(NEW.decision_reason,'')))<3) THEN
  RAISE EXCEPTION 'A decision needs its actor, time and reason' USING ERRCODE='P0001';
 END IF;
 RETURN NEW;
END $$;
CREATE TRIGGER adjustment_decision_guard BEFORE UPDATE OR DELETE ON payroll_attendance_adjustments FOR EACH ROW EXECUTE FUNCTION attendance_decision_guard();

CREATE FUNCTION attendance_punch_evidence_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF TG_OP='DELETE' THEN RAISE EXCEPTION 'Attendance evidence cannot be deleted; request a correction' USING ERRCODE='P0001'; END IF;
 IF OLD.punch_in_time IS NOT NULL AND
   (to_jsonb(NEW)-ARRAY['punch_out_time','punch_out_lat','punch_out_lng','punch_out_address','punch_out_photo','punch_out_accuracy','total_hours','capture_state','review_state']) IS DISTINCT FROM
   (to_jsonb(OLD)-ARRAY['punch_out_time','punch_out_lat','punch_out_lng','punch_out_address','punch_out_photo','punch_out_accuracy','total_hours','capture_state','review_state']) THEN
   RAISE EXCEPTION 'Original check-in evidence cannot be changed' USING ERRCODE='P0001';
 END IF;
 IF OLD.punch_out_time IS NOT NULL AND
   (to_jsonb(NEW)-ARRAY['capture_state','review_state']) IS DISTINCT FROM (to_jsonb(OLD)-ARRAY['capture_state','review_state']) THEN
   RAISE EXCEPTION 'Original checkout evidence cannot be changed' USING ERRCODE='P0001';
 END IF;
 RETURN NEW;
END $$;
CREATE TRIGGER punch_evidence_guard BEFORE UPDATE OR DELETE ON attendance FOR EACH ROW EXECUTE FUNCTION attendance_punch_evidence_guard();

CREATE FUNCTION attendance_leave_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 PERFORM pg_advisory_xact_lock(7430,1);
 IF TG_OP<>'INSERT' AND OLD.status<>'pending' THEN RAISE EXCEPTION 'Decided leave is immutable; submit a leave amendment' USING ERRCODE='P0001'; END IF;
 IF TG_OP='DELETE' THEN RETURN OLD; END IF;
 IF NEW.from_date>NEW.to_date OR NEW.days<=0 OR NEW.hours<0 THEN RAISE EXCEPTION 'Invalid leave dates or quantities' USING ERRCODE='P0001'; END IF;
 IF NEW.status IN ('approved','pending') AND EXISTS(SELECT 1 FROM leave_requests l WHERE l.user_id=NEW.user_id AND l.id<>NEW.id AND l.status IN ('approved','pending') AND l.from_date<=NEW.to_date AND l.to_date>=NEW.from_date
 AND NOT EXISTS(SELECT 1 FROM attendance_requests r WHERE r.kind='leave_amendment' AND r.status='approved' AND (r.proposed->>'leave_id')::bigint=l.id)) THEN
  RAISE EXCEPTION 'Overlapping leave exists; amend that request instead' USING ERRCODE='P0001';
 END IF;
 RETURN NEW;
END $$;
CREATE TRIGGER leave_evidence_guard BEFORE INSERT OR UPDATE OR DELETE ON leave_requests FOR EACH ROW EXECUTE FUNCTION attendance_leave_guard();


-- ------------------------------------------
-- Migration: 20260917000500_attendance_adjustment_retry.sql
-- ------------------------------------------
-- Rejected requests remain visible, but a corrected proposal may be submitted.
-- Only one pending/approved adjustment may exist for a source revision.
DO $$ DECLARE c record; BEGIN
 FOR c IN SELECT conname FROM pg_constraint WHERE conrelid='payroll_attendance_adjustments'::regclass AND contype='u' LOOP
  EXECUTE format('ALTER TABLE payroll_attendance_adjustments DROP CONSTRAINT %I',c.conname);
 END LOOP;
END $$;
CREATE UNIQUE INDEX attendance_adjustment_active_revision
 ON payroll_attendance_adjustments(employee_id,source_month,source_revision)
 WHERE status IN ('pending','approved');


-- ------------------------------------------
-- Migration: 20260918000100_employee_workflows.sql
-- ------------------------------------------
-- Additive workflow upgrade. Existing task/ticket IDs and checklist history remain intact.
ALTER TABLE delegations ADD COLUMN IF NOT EXISTS branch_id bigint REFERENCES attendance_branches(id);
ALTER TABLE delegations ADD COLUMN IF NOT EXISTS work_version integer NOT NULL DEFAULT 1;
ALTER TABLE delegations ADD COLUMN IF NOT EXISTS work_meta jsonb NOT NULL DEFAULT '{}';
ALTER TABLE support_tickets ADD COLUMN IF NOT EXISTS branch_id bigint REFERENCES attendance_branches(id);
ALTER TABLE support_tickets ADD COLUMN IF NOT EXISTS work_version integer NOT NULL DEFAULT 1;
ALTER TABLE support_tickets ADD COLUMN IF NOT EXISTS work_meta jsonb NOT NULL DEFAULT '{}';
ALTER TABLE checklists ADD COLUMN IF NOT EXISTS branch_id bigint REFERENCES attendance_branches(id);
ALTER TABLE checklists ADD COLUMN IF NOT EXISTS work_version integer NOT NULL DEFAULT 1;
ALTER TABLE checklists ADD COLUMN IF NOT EXISTS work_meta jsonb NOT NULL DEFAULT '{}';

-- Only replace status checks, preserving every other existing constraint.
DO $$ DECLARE c record; BEGIN
 FOR c IN SELECT conrelid::regclass AS tbl,conname FROM pg_constraint
 WHERE contype='c' AND conrelid IN ('delegations'::regclass,'support_tickets'::regclass)
 AND (pg_get_constraintdef(oid) ~ '\mstatus\M' OR (conrelid='support_tickets'::regclass AND pg_get_constraintdef(oid) ~ '\m(category|priority)\M')) LOOP
   EXECUTE format('ALTER TABLE %s DROP CONSTRAINT %I',c.tbl,c.conname);
 END LOOP;
END $$;
ALTER TABLE delegations ADD CONSTRAINT delegation_work_status CHECK(status IN ('pending','in_progress','blocked','submitted','approved','rejected','cancelled')) NOT VALID;
ALTER TABLE support_tickets ADD CONSTRAINT ticket_work_status CHECK(status IN ('open','assigned','in_progress','waiting','resolved','closed')) NOT VALID;

CREATE TABLE work_settings (
 id integer PRIMARY KEY CHECK(id=1), version integer NOT NULL DEFAULT 1,
 value jsonb NOT NULL, updated_by bigint REFERENCES users(id), updated_at timestamptz NOT NULL DEFAULT now()
);
INSERT INTO work_settings(id,value) VALUES(1,'{
 "priorities":[{"id":"low","label":"Low","active":true},{"id":"medium","label":"Medium","active":true},{"id":"high","label":"High","active":true},{"id":"urgent","label":"Urgent","active":true}],
 "categories":[{"id":"general","label":"General help","active":true,"assignee_id":null,"response_minutes":null,"resolution_minutes":null,"escalation_ids":[]}],
 "task_review_required":true,"task_evidence_required":true,"requester_can_close":true,"requester_can_reopen":true,
 "pause_waiting":true,"notifications_enabled":true,"escalations_enabled":false
}');

CREATE TABLE work_checklist_versions (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 checklist_id bigint NOT NULL REFERENCES checklists(id), version integer NOT NULL,
 definition jsonb NOT NULL, created_by bigint NOT NULL REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(),
 UNIQUE(checklist_id,version)
);
CREATE TABLE work_occurrences (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 checklist_id bigint NOT NULL REFERENCES checklists(id), template_version_id bigint NOT NULL REFERENCES work_checklist_versions(id),
 title text NOT NULL, description text, assigned_to bigint NOT NULL REFERENCES users(id), created_by bigint NOT NULL REFERENCES users(id),
 branch_id bigint REFERENCES attendance_branches(id), work_date date NOT NULL, due_at timestamptz NOT NULL,
 status text NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','in_progress','submitted','approved','rejected')),
 work_version integer NOT NULL DEFAULT 1, work_meta jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now(),
 UNIQUE(checklist_id,assigned_to,work_date)
);
CREATE TABLE work_events (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, kind text NOT NULL, record_id bigint NOT NULL,
 actor_id bigint REFERENCES users(id), action text NOT NULL, internal boolean NOT NULL DEFAULT false,
 detail jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX work_events_record ON work_events(kind,record_id,id);
CREATE TABLE work_requests (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id bigint NOT NULL REFERENCES users(id), request_id text NOT NULL,
 fingerprint text NOT NULL, response jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(user_id,request_id)
);
CREATE TABLE work_files (
 id uuid PRIMARY KEY, kind text NOT NULL, record_id bigint NOT NULL, uploaded_by bigint NOT NULL REFERENCES users(id),
 name text NOT NULL, mime text NOT NULL, size integer NOT NULL CHECK(size BETWEEN 1 AND 5242880), storage_path text NOT NULL UNIQUE,
 internal boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX work_files_record ON work_files(kind,record_id);
CREATE TABLE work_job_runs (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, started_at timestamptz NOT NULL DEFAULT now(), finished_at timestamptz,
 actor_id bigint REFERENCES users(id), result jsonb
);

CREATE FUNCTION work_keep_history() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
 RAISE EXCEPTION 'Workflow history is append-only';
END $$;
CREATE TRIGGER work_versions_immutable BEFORE UPDATE OR DELETE ON work_checklist_versions FOR EACH ROW EXECUTE FUNCTION work_keep_history();
CREATE TRIGGER work_events_immutable BEFORE UPDATE OR DELETE ON work_events FOR EACH ROW EXECUTE FUNCTION work_keep_history();
CREATE INDEX work_occurrences_due ON work_occurrences(assigned_to,work_date,status);
CREATE INDEX work_tasks_branch ON delegations(branch_id,assigned_to);
CREATE INDEX work_tickets_branch ON support_tickets(branch_id,user_id);
DO $$ DECLARE t text; BEGIN
 FOREACH t IN ARRAY ARRAY['work_settings','work_checklist_versions','work_occurrences','work_events','work_requests','work_files','work_job_runs'] LOOP
 EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY',t);
 EXECUTE format('REVOKE ALL ON %I FROM anon,authenticated',t);
 END LOOP;
END $$;
INSERT INTO storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
VALUES('work-evidence','work-evidence',false,5242880,ARRAY['image/jpeg','image/png','application/pdf','text/plain'])
ON CONFLICT(id) DO UPDATE SET public=false,file_size_limit=5242880,allowed_mime_types=EXCLUDED.allowed_mime_types;

-- Explicit shared roles only. No implied admin-label bypass and no employee grants.
INSERT INTO roles(name,description,is_system) VALUES('Workflows owner','Owner-controlled task, checklist, ticket and configuration access',1) ON CONFLICT(name) DO NOTHING;
INSERT INTO role_permissions(role_id,module,can_view,can_create,can_edit,can_delete,can_approve,can_see_all,scope_mode)
SELECT r.id,m.module,1,1,1,1,1,1,'all' FROM roles r CROSS JOIN (VALUES('delegations'),('checklists'),('help_tickets'),('work_settings')) m(module)
WHERE r.name='Workflows owner' ON CONFLICT(role_id,module) DO NOTHING;
INSERT INTO user_roles(user_id,role_id) SELECT p.user_id,r.id FROM attendance_permission_managers p CROSS JOIN roles r WHERE r.name='Workflows owner' ON CONFLICT DO NOTHING;
INSERT INTO roles(name,description,is_system) VALUES('Employee work self-service','Own tasks, assigned checklist occurrences, and own help tickets',1) ON CONFLICT(name) DO NOTHING;
INSERT INTO role_permissions(role_id,module,can_view,can_create,can_edit,can_delete,can_approve,can_see_all,scope_mode)
SELECT r.id,m.module,1,CASE WHEN m.module='help_tickets' THEN 1 ELSE 0 END,1,0,0,0,'self'
FROM roles r CROSS JOIN (VALUES('delegations'),('checklists'),('help_tickets')) m(module)
WHERE r.name='Employee work self-service' ON CONFLICT(role_id,module) DO NOTHING;
-- The owner assigns this role deliberately in Users. No automatic changes to staff permissions.


-- ------------------------------------------
-- Migration: 20260918000200_workflow_file_retries.sql
-- ------------------------------------------
ALTER TABLE work_files ADD COLUMN payload_hash text;


-- ------------------------------------------
-- Migration: 20260918000300_role_dashboards.sql
-- ------------------------------------------
-- Dashboard entry is available to every existing role. Cards still require
-- their source-module grants; this does not grant financial or staff access.
INSERT INTO role_permissions(role_id,module,can_view,can_create,can_edit,can_delete,can_approve,can_see_all,scope_mode,scope_branches)
SELECT id,'dashboard',1,0,0,0,0,0,'self','[]' FROM roles
ON CONFLICT(role_id,module) DO UPDATE SET can_view=1;


