-- AT-01/02/03. Incremental, non-destructive. Never use the local baseline in production.
-- Hosted execution requires a reviewed owner: SET attendance.bootstrap_user_id = '<existing user id>';
-- Local setup may bootstrap ONLY the deliberately seeded local-admin in the marked local database.
CREATE TABLE IF NOT EXISTS attendance_permission_managers (
  user_id bigint PRIMARY KEY REFERENCES users(id), granted_at timestamptz NOT NULL DEFAULT now()
);
DO $$
DECLARE owner_id bigint;
BEGIN
  owner_id := nullif(current_setting('attendance.bootstrap_user_id', true), '')::bigint;
  IF owner_id IS NULL AND EXISTS (SELECT 1 FROM app_settings WHERE key='local_environment' AND value='sotyn-headmasters-local') THEN
    SELECT id INTO owner_id FROM users WHERE username='local-admin' AND active=1;
  END IF;
  IF owner_id IS NOT NULL THEN
    IF NOT EXISTS (SELECT 1 FROM users WHERE id=owner_id AND active=1 AND COALESCE(archived,0)=0) THEN
      RAISE EXCEPTION 'Bootstrap owner must be an existing active, nonarchived login';
    END IF;
    INSERT INTO attendance_permission_managers(user_id) VALUES(owner_id) ON CONFLICT DO NOTHING;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM attendance_permission_managers) THEN
    RAISE EXCEPTION 'Nominate and verify a permission owner with attendance.bootstrap_user_id before this migration';
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS attendance_branches (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL UNIQUE, name text NOT NULL, active integer NOT NULL DEFAULT 1 CHECK(active IN (0,1))
);
ALTER TABLE employees ADD COLUMN IF NOT EXISTS attendance_branch_id bigint REFERENCES attendance_branches(id);
ALTER TABLE geofence_settings ADD COLUMN IF NOT EXISTS attendance_branch_id bigint REFERENCES attendance_branches(id);
ALTER TABLE role_permissions ADD COLUMN IF NOT EXISTS scope_mode text NOT NULL DEFAULT 'self' CHECK(scope_mode IN ('self','team','branch','all'));
ALTER TABLE role_permissions ADD COLUMN IF NOT EXISTS scope_branches text NOT NULL DEFAULT '[]';
UPDATE role_permissions SET scope_mode='all' WHERE can_see_all=1;

-- Keep existing action grants. New actions inherit only their explicitly stored predecessor grants.
INSERT INTO role_permissions(role_id,module,can_view,can_create,can_edit,can_delete,can_approve,can_see_all,scope_mode,scope_branches)
SELECT p.role_id,m.target,p.can_view,p.can_create,p.can_edit,p.can_delete,p.can_approve,p.can_see_all,p.scope_mode,p.scope_branches
FROM role_permissions p JOIN (VALUES
 ('attendance','attendance_capture'), ('attendance','attendance_corrections'),
 ('attendance','attendance_locations'), ('attendance','attendance_tracking'),
 ('employees','employee_shifts'), ('employees','employee_links'), ('payroll','attendance_rules')
) AS m(source,target) ON p.module=m.source
ON CONFLICT(role_id,module) DO NOTHING;

INSERT INTO roles(name,description,is_system) VALUES('Attendance foundation owner','Explicit, revocable attendance grants for the nominated permission owner',1) ON CONFLICT(name) DO NOTHING;
INSERT INTO role_permissions(role_id,module,can_view,can_create,can_edit,can_delete,can_approve,can_see_all,scope_mode)
SELECT r.id,m.module,1,1,1,1,1,1,'all' FROM roles r CROSS JOIN (VALUES
 ('attendance'),('employees'),('payroll'),('attendance_capture'),('attendance_corrections'),
 ('attendance_locations'),('attendance_tracking'),('employee_shifts'),('employee_links'),('attendance_rules')
) AS m(module) WHERE r.name='Attendance foundation owner' ON CONFLICT(role_id,module) DO NOTHING;
INSERT INTO user_roles(user_id,role_id)
SELECT o.user_id,r.id FROM attendance_permission_managers o CROSS JOIN roles r WHERE r.name='Attendance foundation owner'
ON CONFLICT(user_id,role_id) DO NOTHING;

-- Widen only integer columns. Do not presume a hosted decimal column is defective.
DO $$ BEGIN
 IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='leave_requests' AND column_name='days' AND data_type IN ('smallint','integer','bigint')) THEN
   ALTER TABLE leave_requests ALTER COLUMN days TYPE numeric USING days::numeric;
 END IF;
END $$;
INSERT INTO payroll_settings(id) VALUES(1) ON CONFLICT(id) DO NOTHING;

-- Keep every original attendance row. Legacy rows are intentionally outside new-session uniqueness.
ALTER TABLE attendance ADD COLUMN IF NOT EXISTS capture_session integer;
ALTER TABLE attendance ADD COLUMN IF NOT EXISTS capture_state text;
CREATE UNIQUE INDEX IF NOT EXISTS attendance_session_identity ON attendance(user_id,date,capture_session) WHERE capture_session IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS attendance_one_open_session ON attendance(user_id) WHERE capture_state='open';
CREATE TABLE IF NOT EXISTS attendance_capture_events (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_id bigint NOT NULL REFERENCES users(id), request_id text NOT NULL,
 attendance_id bigint NOT NULL REFERENCES attendance(id), kind text NOT NULL CHECK(kind IN ('in','out')),
 captured_at timestamptz NOT NULL, received_at timestamptz NOT NULL DEFAULT now(),
 payload_hash text NOT NULL, evidence jsonb NOT NULL,
 UNIQUE(user_id,request_id), UNIQUE(attendance_id,kind)
);
-- No automatic cleanup/guessing; this view is the migration/linkage review queue.
CREATE OR REPLACE VIEW attendance_foundation_conflicts AS
 SELECT 'duplicate_attendance_day'::text AS kind, user_id::text AS subject, date::text AS detail, count(*) AS records
 FROM attendance WHERE user_id IS NOT NULL GROUP BY user_id,date HAVING count(*)>1
 UNION ALL SELECT 'ambiguous_employee_login',user_id::text,''::text,count(*) FROM employees WHERE user_id IS NOT NULL GROUP BY user_id HAVING count(*)>1
 UNION ALL SELECT 'unlinked_employee',id::text,name::text,1::bigint FROM employees WHERE user_id IS NULL;

CREATE INDEX IF NOT EXISTS employee_attendance_branch ON employees(attendance_branch_id,user_id);
CREATE INDEX IF NOT EXISTS employee_attendance_managers ON employees(reporting_manager_id_1,reporting_manager_id_2);
ALTER TABLE attendance_permission_managers ENABLE ROW LEVEL SECURITY;
ALTER TABLE attendance_branches ENABLE ROW LEVEL SECURITY;
ALTER TABLE attendance_capture_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON attendance_foundation_conflicts FROM anon, authenticated;
