-- Additive workflow upgrade. Existing task/ticket IDs and checklist history remain intact.
ALTER TABLE delegations ADD COLUMN IF NOT EXISTS branch_id bigint REFERENCES attendance_branches(id);
ALTER TABLE delegations ADD COLUMN IF NOT EXISTS work_version integer NOT NULL DEFAULT 1;
ALTER TABLE delegations ADD COLUMN IF NOT EXISTS work_meta jsonb NOT NULL DEFAULT '{}';
ALTER TABLE support_tickets ADD COLUMN IF NOT EXISTS branch_id bigint REFERENCES attendance_branches(id);
ALTER TABLE support_tickets ADD COLUMN IF NOT EXISTS work_version integer NOT NULL DEFAULT 1;
ALTER TABLE support_tickets ADD COLUMN IF NOT EXISTS work_meta jsonb NOT NULL DEFAULT '{}';
ALTER TABLE checklists ADD COLUMN IF NOT EXISTS branch_id bigint REFERENCES attendance_branches(id);
ALTER TABLE checklists ADD COLUMN IF NOT EXISTS work_version integer NOT NULL DEFAULT 1;
ALTER TABLE checklists ADD COLUMN IF NOT EXISTS work_meta jsonb NOT NULL DEFAULT '{}';

-- Only replace status checks, preserving every other existing constraint.
DO $$ DECLARE c record; BEGIN
 FOR c IN SELECT conrelid::regclass AS tbl,conname FROM pg_constraint
 WHERE contype='c' AND conrelid IN ('delegations'::regclass,'support_tickets'::regclass)
 AND (pg_get_constraintdef(oid) ~ '\mstatus\M' OR (conrelid='support_tickets'::regclass AND pg_get_constraintdef(oid) ~ '\m(category|priority)\M')) LOOP
   EXECUTE format('ALTER TABLE %s DROP CONSTRAINT %I',c.tbl,c.conname);
 END LOOP;
END $$;
ALTER TABLE delegations ADD CONSTRAINT delegation_work_status CHECK(status IN ('pending','in_progress','blocked','submitted','approved','rejected','cancelled')) NOT VALID;
ALTER TABLE support_tickets ADD CONSTRAINT ticket_work_status CHECK(status IN ('open','assigned','in_progress','waiting','resolved','closed')) NOT VALID;

CREATE TABLE work_settings (
 id integer PRIMARY KEY CHECK(id=1), version integer NOT NULL DEFAULT 1,
 value jsonb NOT NULL, updated_by bigint REFERENCES users(id), updated_at timestamptz NOT NULL DEFAULT now()
);
INSERT INTO work_settings(id,value) VALUES(1,'{
 "priorities":[{"id":"low","label":"Low","active":true},{"id":"medium","label":"Medium","active":true},{"id":"high","label":"High","active":true},{"id":"urgent","label":"Urgent","active":true}],
 "categories":[{"id":"general","label":"General help","active":true,"assignee_id":null,"response_minutes":null,"resolution_minutes":null,"escalation_ids":[]}],
 "task_review_required":true,"task_evidence_required":true,"requester_can_close":true,"requester_can_reopen":true,
 "pause_waiting":true,"notifications_enabled":true,"escalations_enabled":false
}');

CREATE TABLE work_checklist_versions (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 checklist_id bigint NOT NULL REFERENCES checklists(id), version integer NOT NULL,
 definition jsonb NOT NULL, created_by bigint NOT NULL REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(),
 UNIQUE(checklist_id,version)
);
CREATE TABLE work_occurrences (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 checklist_id bigint NOT NULL REFERENCES checklists(id), template_version_id bigint NOT NULL REFERENCES work_checklist_versions(id),
 title text NOT NULL, description text, assigned_to bigint NOT NULL REFERENCES users(id), created_by bigint NOT NULL REFERENCES users(id),
 branch_id bigint REFERENCES attendance_branches(id), work_date date NOT NULL, due_at timestamptz NOT NULL,
 status text NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','in_progress','submitted','approved','rejected')),
 work_version integer NOT NULL DEFAULT 1, work_meta jsonb NOT NULL DEFAULT '{}', created_at timestamptz NOT NULL DEFAULT now(),
 UNIQUE(checklist_id,assigned_to,work_date)
);
CREATE TABLE work_events (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, kind text NOT NULL, record_id bigint NOT NULL,
 actor_id bigint REFERENCES users(id), action text NOT NULL, internal boolean NOT NULL DEFAULT false,
 detail jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX work_events_record ON work_events(kind,record_id,id);
CREATE TABLE work_requests (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id bigint NOT NULL REFERENCES users(id), request_id text NOT NULL,
 fingerprint text NOT NULL, response jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(user_id,request_id)
);
CREATE TABLE work_files (
 id uuid PRIMARY KEY, kind text NOT NULL, record_id bigint NOT NULL, uploaded_by bigint NOT NULL REFERENCES users(id),
 name text NOT NULL, mime text NOT NULL, size integer NOT NULL CHECK(size BETWEEN 1 AND 5242880), storage_path text NOT NULL UNIQUE,
 internal boolean NOT NULL DEFAULT false, created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX work_files_record ON work_files(kind,record_id);
CREATE TABLE work_job_runs (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, started_at timestamptz NOT NULL DEFAULT now(), finished_at timestamptz,
 actor_id bigint REFERENCES users(id), result jsonb
);

CREATE FUNCTION work_keep_history() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
 RAISE EXCEPTION 'Workflow history is append-only';
END $$;
CREATE TRIGGER work_versions_immutable BEFORE UPDATE OR DELETE ON work_checklist_versions FOR EACH ROW EXECUTE FUNCTION work_keep_history();
CREATE TRIGGER work_events_immutable BEFORE UPDATE OR DELETE ON work_events FOR EACH ROW EXECUTE FUNCTION work_keep_history();
CREATE INDEX work_occurrences_due ON work_occurrences(assigned_to,work_date,status);
CREATE INDEX work_tasks_branch ON delegations(branch_id,assigned_to);
CREATE INDEX work_tickets_branch ON support_tickets(branch_id,user_id);
DO $$ DECLARE t text; BEGIN
 FOREACH t IN ARRAY ARRAY['work_settings','work_checklist_versions','work_occurrences','work_events','work_requests','work_files','work_job_runs'] LOOP
 EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY',t);
 EXECUTE format('REVOKE ALL ON %I FROM anon,authenticated',t);
 END LOOP;
END $$;
INSERT INTO storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
VALUES('work-evidence','work-evidence',false,5242880,ARRAY['image/jpeg','image/png','application/pdf','text/plain'])
ON CONFLICT(id) DO UPDATE SET public=false,file_size_limit=5242880,allowed_mime_types=EXCLUDED.allowed_mime_types;

-- Explicit shared roles only. No implied admin-label bypass and no employee grants.
INSERT INTO roles(name,description,is_system) VALUES('Workflows owner','Owner-controlled task, checklist, ticket and configuration access',1) ON CONFLICT(name) DO NOTHING;
INSERT INTO role_permissions(role_id,module,can_view,can_create,can_edit,can_delete,can_approve,can_see_all,scope_mode)
SELECT r.id,m.module,1,1,1,1,1,1,'all' FROM roles r CROSS JOIN (VALUES('delegations'),('checklists'),('help_tickets'),('work_settings')) m(module)
WHERE r.name='Workflows owner' ON CONFLICT(role_id,module) DO NOTHING;
INSERT INTO user_roles(user_id,role_id) SELECT p.user_id,r.id FROM attendance_permission_managers p CROSS JOIN roles r WHERE r.name='Workflows owner' ON CONFLICT DO NOTHING;
INSERT INTO roles(name,description,is_system) VALUES('Employee work self-service','Own tasks, assigned checklist occurrences, and own help tickets',1) ON CONFLICT(name) DO NOTHING;
INSERT INTO role_permissions(role_id,module,can_view,can_create,can_edit,can_delete,can_approve,can_see_all,scope_mode)
SELECT r.id,m.module,1,CASE WHEN m.module='help_tickets' THEN 1 ELSE 0 END,1,0,0,0,'self'
FROM roles r CROSS JOIN (VALUES('delegations'),('checklists'),('help_tickets')) m(module)
WHERE r.name='Employee work self-service' ON CONFLICT(role_id,module) DO NOTHING;
-- The owner assigns this role deliberately in Users. No automatic changes to staff permissions.
