-- Additive attendance operations. No historical attendance is deleted or recalculated.
ALTER TABLE employees ADD COLUMN IF NOT EXISTS employment_end_date text;
ALTER TABLE attendance ADD COLUMN IF NOT EXISTS employee_id bigint REFERENCES employees(id);
ALTER TABLE attendance ADD COLUMN IF NOT EXISTS shift_snapshot jsonb;
ALTER TABLE attendance ADD COLUMN IF NOT EXISTS policy_version_id bigint;
ALTER TABLE attendance ADD COLUMN IF NOT EXISTS review_state text NOT NULL DEFAULT 'accepted' CHECK(review_state IN ('accepted','pending','rejected'));
ALTER TABLE payroll_runs ADD COLUMN IF NOT EXISTS snapshot_json jsonb;
ALTER TABLE payroll_runs ADD COLUMN IF NOT EXISTS attendance_revision integer NOT NULL DEFAULT 1;

CREATE TABLE attendance_policy_versions (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 effective_from text NOT NULL CHECK(effective_from ~ '^\d{4}-\d{2}-\d{2}$'),
 rules jsonb NOT NULL, reason text NOT NULL, created_by bigint REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE attendance ADD CONSTRAINT attendance_policy_version_fk FOREIGN KEY(policy_version_id) REFERENCES attendance_policy_versions(id);
CREATE TABLE attendance_shift_templates (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, code text NOT NULL, version integer NOT NULL,
 name text NOT NULL, segments jsonb NOT NULL, week_off_days jsonb NOT NULL,
 created_by bigint REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(code,version)
);
CREATE TABLE attendance_roster_batches (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, request_id text NOT NULL UNIQUE,
 payload_hash text NOT NULL, created_by bigint REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(), row_count integer NOT NULL
);
CREATE TABLE attendance_roster_entries (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, employee_id bigint NOT NULL REFERENCES employees(id),
 work_date text NOT NULL, day_type text NOT NULL CHECK(day_type IN ('work','off')),
 template_id bigint REFERENCES attendance_shift_templates(id), reason text NOT NULL,
 batch_id bigint REFERENCES attendance_roster_batches(id), created_by bigint REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now(),
 CHECK(day_type='off' OR template_id IS NOT NULL)
);
CREATE INDEX attendance_roster_lookup ON attendance_roster_entries(employee_id,work_date,id DESC);
CREATE TABLE attendance_requests (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, request_id text NOT NULL, payload_hash text NOT NULL,
 employee_id bigint NOT NULL REFERENCES employees(id), work_date text NOT NULL,
 kind text NOT NULL CHECK(kind IN ('correction','capture_exception')),
 proposed jsonb NOT NULL, reason text NOT NULL, requested_by bigint NOT NULL REFERENCES users(id),
 requested_at timestamptz NOT NULL DEFAULT now(), status text NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','approved','rejected')),
 decided_by bigint REFERENCES users(id), decided_at timestamptz, decision_reason text,
 UNIQUE(requested_by,request_id), CHECK(decided_by IS NULL OR decided_by<>requested_by)
);
CREATE INDEX attendance_requests_day ON attendance_requests(employee_id,work_date,id DESC);
CREATE TABLE attendance_periods (
 month text PRIMARY KEY CHECK(month ~ '^\d{4}-(0[1-9]|1[0-2])$'),
 state text NOT NULL CHECK(state IN ('open','closed')), revision integer NOT NULL DEFAULT 1,
 changed_by bigint REFERENCES users(id), changed_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE attendance_period_events (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, month text NOT NULL REFERENCES attendance_periods(month),
 revision integer NOT NULL, action text NOT NULL, reason text NOT NULL, actor_id bigint REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE attendance_month_snapshots (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, month text NOT NULL, revision integer NOT NULL,
 employee_id bigint NOT NULL REFERENCES employees(id), payload jsonb NOT NULL, created_by bigint REFERENCES users(id),
 created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(month,revision,employee_id)
);
CREATE TABLE payroll_snapshot_history (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, payroll_run_id bigint REFERENCES payroll_runs(id),
 month text NOT NULL, employee_id bigint REFERENCES employees(id), payload jsonb NOT NULL,
 provenance text NOT NULL, actor_id bigint REFERENCES users(id), created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE payroll_attendance_adjustments (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, employee_id bigint NOT NULL REFERENCES employees(id),
 source_month text NOT NULL, source_revision integer NOT NULL, target_month text NOT NULL,
 amount numeric NOT NULL, reason text NOT NULL, created_by bigint NOT NULL REFERENCES users(id),
 status text NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','approved','rejected')),
 decided_by bigint REFERENCES users(id), decided_at timestamptz,
 UNIQUE(employee_id,source_month,source_revision), CHECK(decided_by IS NULL OR decided_by<>created_by), CHECK(target_month>source_month)
);
-- Preserve existing payroll as it was stored. Do not fabricate missing historical inputs.
INSERT INTO payroll_snapshot_history(payroll_run_id,month,employee_id,payload,provenance)
SELECT id,month,employee_id,to_jsonb(p),'legacy snapshot; historical policy inputs may be unavailable' FROM payroll_runs p;
INSERT INTO attendance_periods(month,state)
SELECT DISTINCT month,'closed' FROM payroll_runs WHERE status IN ('finalised','disbursed') OR paid=1 ON CONFLICT DO NOTHING;

CREATE FUNCTION attendance_immutable() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN RAISE EXCEPTION 'Original evidence and published versions are immutable; create an amendment' USING ERRCODE='P0001'; END $$;
DO $$ DECLARE t text; BEGIN
 FOREACH t IN ARRAY ARRAY['attendance_capture_events','attendance_policy_versions','attendance_shift_templates','attendance_roster_entries','attendance_roster_batches','attendance_period_events','attendance_month_snapshots','payroll_snapshot_history'] LOOP
  EXECUTE format('CREATE TRIGGER immutable_record BEFORE UPDATE OR DELETE ON %I FOR EACH ROW EXECUTE FUNCTION attendance_immutable()',t);
 END LOOP;
END $$;

-- All attendance writers and period closure serialize on this lock. Checks are
-- repeated in the DB so an old client cannot race a period closure.
CREATE FUNCTION attendance_assert_open(d text) RETURNS void LANGUAGE plpgsql AS $$
BEGIN
 PERFORM pg_advisory_xact_lock(7430,1);
 IF EXISTS(SELECT 1 FROM attendance_periods WHERE month=left(d,7) AND state='closed') THEN
  RAISE EXCEPTION 'Attendance period % is closed; an authorized reopen is required',left(d,7) USING ERRCODE='P0001';
 END IF;
END $$;
CREATE FUNCTION attendance_period_guard() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE a jsonb; b jsonb; lo text; hi text; p record;
BEGIN
 PERFORM pg_advisory_xact_lock(7430,1);
 IF TG_OP<>'INSERT' THEN a:=to_jsonb(OLD); END IF;
 IF TG_OP<>'DELETE' THEN b:=to_jsonb(NEW); END IF;
 FOR p IN SELECT x FROM (VALUES(a),(b)) v(x) WHERE x IS NOT NULL LOOP
  IF TG_TABLE_NAME='attendance' THEN PERFORM attendance_assert_open(p.x->>'date');
  ELSIF TG_TABLE_NAME IN ('attendance_roster_entries','attendance_requests') THEN PERFORM attendance_assert_open(p.x->>'work_date');
  ELSIF TG_TABLE_NAME IN ('payroll_advances','payroll_attendance_adjustments') THEN PERFORM attendance_assert_open(COALESCE(p.x->>'target_month',p.x->>'month')||'-01');
  ELSIF TG_TABLE_NAME='leave_requests' THEN
   lo:=p.x->>'from_date'; hi:=COALESCE(p.x->>'to_date',lo);
   IF EXISTS(SELECT 1 FROM attendance_periods WHERE state='closed' AND month BETWEEN left(lo,7) AND left(hi,7)) THEN RAISE EXCEPTION 'Leave overlaps a closed attendance period' USING ERRCODE='P0001'; END IF;
  ELSE
   IF EXISTS(SELECT 1 FROM attendance_periods WHERE state='closed' AND month>=left(p.x->>'effective_from',7)) THEN RAISE EXCEPTION 'Effective date affects a closed attendance period' USING ERRCODE='P0001'; END IF;
  END IF;
 END LOOP;
 IF TG_OP='DELETE' THEN RETURN OLD; END IF; RETURN NEW;
END $$;
DO $$ DECLARE t text; BEGIN
 FOREACH t IN ARRAY ARRAY['attendance','leave_requests','employee_shifts','attendance_roster_entries','attendance_requests','attendance_policy_versions','payroll_advances','payroll_attendance_adjustments'] LOOP
  EXECUTE format('CREATE TRIGGER period_guard BEFORE INSERT OR UPDATE OR DELETE ON %I FOR EACH ROW EXECUTE FUNCTION attendance_period_guard()',t);
 END LOOP;
END $$;
CREATE FUNCTION attendance_decision_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF TG_OP='DELETE' OR OLD.status<>'pending' THEN RAISE EXCEPTION 'Decisions are preserved; submit a new amendment' USING ERRCODE='P0001'; END IF;
 IF NEW.proposed IS DISTINCT FROM OLD.proposed OR NEW.requested_by<>OLD.requested_by OR NEW.employee_id<>OLD.employee_id OR NEW.work_date<>OLD.work_date THEN RAISE EXCEPTION 'Original request must be preserved' USING ERRCODE='P0001'; END IF;
 RETURN NEW;
END $$;
CREATE TRIGGER decision_guard BEFORE UPDATE OR DELETE ON attendance_requests FOR EACH ROW EXECUTE FUNCTION attendance_decision_guard();
CREATE FUNCTION payroll_evidence_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 PERFORM pg_advisory_xact_lock(7430,1);
 IF TG_OP='DELETE' THEN RAISE EXCEPTION 'Payroll snapshots cannot be deleted' USING ERRCODE='P0001'; END IF;
 IF TG_OP='UPDATE' AND (OLD.paid=1 OR OLD.status='disbursed') AND NEW IS DISTINCT FROM OLD THEN RAISE EXCEPTION 'Paid payroll is immutable; use a later adjustment' USING ERRCODE='P0001'; END IF;
 IF TG_OP='UPDATE' AND OLD.status='finalised' AND
  (to_jsonb(NEW)-ARRAY['paid','paid_at','paid_by','status']) IS DISTINCT FROM (to_jsonb(OLD)-ARRAY['paid','paid_at','paid_by','status']) THEN
  RAISE EXCEPTION 'Finalised payroll inputs cannot be overwritten' USING ERRCODE='P0001';
 END IF;
 RETURN NEW;
END $$;
CREATE TRIGGER payroll_evidence_guard BEFORE UPDATE OR DELETE ON payroll_runs FOR EACH ROW EXECUTE FUNCTION payroll_evidence_guard();

INSERT INTO role_permissions(role_id,module,can_view,can_create,can_edit,can_delete,can_approve,can_see_all,scope_mode,scope_branches)
SELECT p.role_id,m.target,p.can_view,p.can_create,p.can_edit,p.can_delete,p.can_approve,p.can_see_all,p.scope_mode,p.scope_branches
FROM role_permissions p JOIN (VALUES('employee_shifts','attendance_rosters'),('attendance_rules','attendance_policies'),('attendance_corrections','attendance_requests'),('payroll','attendance_periods')) m(source,target) ON p.module=m.source
ON CONFLICT DO NOTHING;
INSERT INTO role_permissions(role_id,module,can_view,can_create,scope_mode)
SELECT id,'attendance_requests',1,1,'self' FROM roles WHERE name='Employee attendance self-service' ON CONFLICT DO NOTHING;
DO $$ DECLARE t text; BEGIN
 FOREACH t IN ARRAY ARRAY['attendance_policy_versions','attendance_shift_templates','attendance_roster_batches','attendance_roster_entries','attendance_requests','attendance_periods','attendance_period_events','attendance_month_snapshots','payroll_snapshot_history','payroll_attendance_adjustments'] LOOP
  EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY',t);
 END LOOP;
END $$;
