const fs=require('fs'),assert=require('assert/strict'),crypto=require('crypto');
const {chromium}=require('../../.local/validation/node_modules/playwright');
const fixture=JSON.parse(fs.readFileSync('.local/workflow-fixtures.json','utf8')),base='http://127.0.0.1:54321/functions/v1/api';
let browser;const results=[],pages=[],serverErrors=[];
async function api(token,path,body){const r=await fetch(base+path,{method:body?'POST':'GET',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json','Idempotency-Key':crypto.randomUUID()},...(body?{body:JSON.stringify(body)}:{})});const data=await r.json();assert.ok(r.ok,JSON.stringify(data));return data;}
(async()=>{
 browser=await chromium.launch({channel:'msedge',headless:true});
 async function open(person){
  const session=await api('', '/auth/login',{username:person.username,password:fixture.password});
  const ctx=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
  await ctx.route('**/*',r=>['127.0.0.1','localhost'].includes(new URL(r.request().url()).hostname)?r.continue():r.abort());
  await ctx.addInitScript(t=>localStorage.setItem('token',t),session.token);const page=await ctx.newPage(),errors=[];page.setDefaultTimeout(30000);page.on('pageerror',e=>errors.push(e.message));
  pages.push(page);page.on('response',async r=>{if(r.status()>=500&&r.url().includes('/api/')){serverErrors.push(r.status()+' '+new URL(r.url()).pathname);console.log('HTTP',r.status(),new URL(r.url()).pathname,(await r.text()).slice(0,180));}});return {ctx,page,token:session.token,errors};
 }
 const employee=await open(fixture.a),manager=await open(fixture.manager),tag='Mobile '+Date.now();
 let p=manager.page;await p.goto('http://127.0.0.1:3055/delegations');await p.getByRole('button',{name:'Create task',exact:true}).click();
 await p.getByLabel('Title',{exact:true}).fill(tag+' reception');await p.getByLabel('Instructions / description').fill('Prepare the reception and attach proof');
 await p.getByLabel('Accountable employee',{exact:true}).selectOption(String(fixture.a.uid));
 await p.getByLabel('Deadline (your device timezone)',{exact:true}).fill('2026-12-01T18:00');
 const created=p.waitForResponse(r=>r.url().endsWith('/work/tasks')&&r.request().method()==='POST');await p.getByRole('button',{name:'Save',exact:true}).click();const task=await (await created).json();assert.ok(task.id,JSON.stringify(task));
 p=employee.page;await p.goto(`http://127.0.0.1:3055/delegations?record=${task.id}`);await p.getByRole('button',{name:'Start work',exact:true}).click();await p.getByText('In Progress \u00b7 Record #'+task.id,{exact:true}).waitFor();
 await p.getByLabel('Attach file',{exact:true}).setInputFiles({name:'mobile-proof.txt',mimeType:'text/plain',buffer:Buffer.from('Synthetic mobile evidence')});
 const choice=p.getByLabel('Completion evidence',{exact:true}).locator('option');await choice.first().waitFor();await p.getByLabel('Completion evidence',{exact:true}).selectOption(await choice.first().getAttribute('value'));
 await p.getByLabel('Workflow note',{exact:true}).fill('Reception prepared');await p.getByRole('button',{name:'Submit for review',exact:true}).click();
 await p.getByText('Submitted for Review · Record #'+task.id,{exact:true}).waitFor();
 p=manager.page;await p.reload();await p.goto(`http://127.0.0.1:3055/delegations?record=${task.id}`);await p.getByLabel('Workflow note',{exact:true}).fill('Please confirm all stations');await p.getByRole('button',{name:'Return with reason',exact:true}).click();await p.getByText('Returned · Record #'+task.id,{exact:true}).waitFor();
 p=employee.page;await p.reload();await p.getByRole('button',{name:'Start work',exact:true}).click();await p.getByText('In Progress \u00b7 Record #'+task.id,{exact:true}).waitFor();await p.getByLabel('Workflow note',{exact:true}).fill('All stations confirmed');await p.getByRole('button',{name:'Submit for review',exact:true}).click();await p.getByText('Submitted for Review · Record #'+task.id,{exact:true}).waitFor();
 p=manager.page;await p.reload();await p.getByRole('button',{name:'Approve completion',exact:true}).click();await p.getByText('Completed · Record #'+task.id,{exact:true}).waitFor();results.push('Mobile task creation, private upload, return, correction and approval');console.log('PASS '+results.at(-1));
 const today=new Date(Date.now()+330*60000).toISOString().slice(0,10);
 p=manager.page;await p.goto('http://127.0.0.1:3055/checklists');await p.getByRole('button',{name:'Templates',exact:true}).click();await p.getByRole('button',{name:'Create template',exact:true}).click();
 await p.getByRole('button',{name:'Hygiene checks',exact:true}).click();await p.getByLabel('Template title',{exact:true}).fill(tag+' checklist');await p.getByLabel('Accountable employees (one occurrence each)',{exact:true}).selectOption(String(fixture.a.uid));await p.getByLabel('Item name',{exact:true}).fill('Clean station');await p.getByLabel('Evidence required',{exact:true}).selectOption('note');
 const templateResponse=p.waitForResponse(r=>r.url().endsWith('/work/templates')&&r.request().method()==='POST');await p.getByRole('button',{name:'Save',exact:true}).click();const template=await (await templateResponse).json();assert.ok(template.id,JSON.stringify(template));
 const owner=await api('','/auth/login',JSON.parse(fs.readFileSync('.local/test-login.json','utf8')));await api(owner.token,'/work/jobs/run',{});
 const occurrence=(await api(employee.token,'/work/occurrences?today=1')).rows.find(r=>r.checklist_id===template.id);assert.ok(occurrence);
 p=employee.page;await p.goto(`http://127.0.0.1:3055/checklists?record=${occurrence.id}`);await p.getByLabel('Clean station status',{exact:true}).selectOption('done');await p.getByLabel('Clean station note',{exact:true}).fill('Station disinfected');await p.getByRole('button',{name:'Save progress',exact:true}).click();await p.getByText('In Progress · Record #'+occurrence.id,{exact:true}).waitFor();await p.reload();await p.getByLabel('Clean station note',{exact:true}).waitFor();assert.equal(await p.getByLabel('Clean station note',{exact:true}).inputValue(),'Station disinfected');await p.getByRole('button',{name:'Complete checklist',exact:true}).click();await p.getByText('Completed · Record #'+occurrence.id,{exact:true}).waitFor();results.push('Mobile checklist draft, refresh/resume, required note and completion');console.log('PASS '+results.at(-1));
 p=employee.page;await p.goto('http://127.0.0.1:3055/help-tickets');await p.getByRole('button',{name:'Create ticket',exact:true}).click();await p.getByLabel('Title',{exact:true}).fill(tag+' equipment');await p.getByLabel('Instructions / description').fill('A test equipment fault needs help');
 const ticketResponse=p.waitForResponse(r=>r.url().endsWith('/work/tickets')&&r.request().method()==='POST');await p.getByRole('button',{name:'Save',exact:true}).click();const ticket=await (await ticketResponse).json();assert.ok(ticket.id,JSON.stringify(ticket));
 p=manager.page;await p.goto(`http://127.0.0.1:3055/help-tickets?record=${ticket.id}`);await p.getByLabel('Accountable assignee',{exact:true}).selectOption(String(fixture.manager.uid));await p.getByRole('button',{name:'Assign ticket',exact:true}).click();await p.getByText('Assigned · Record #'+ticket.id,{exact:true}).waitFor();await p.getByRole('button',{name:'Start work',exact:true}).click();await p.getByRole('button',{name:'Resolve ticket',exact:true}).waitFor();await p.getByLabel('Workflow note',{exact:true}).fill('Equipment tested and repaired');await p.getByRole('button',{name:'Resolve ticket',exact:true}).click();await p.getByText('Resolved · Record #'+ticket.id,{exact:true}).waitFor();
 p=employee.page;await p.reload();await p.goto(`http://127.0.0.1:3055/help-tickets?record=${ticket.id}`);await p.getByRole('button',{name:'Close ticket',exact:true}).click();await p.getByText('Closed · Record #'+ticket.id,{exact:true}).waitFor();await p.getByLabel('Workflow note',{exact:true}).fill('Issue returned during test');await p.getByRole('button',{name:'Reopen ticket',exact:true}).click();await p.getByText('Assigned · Record #'+ticket.id,{exact:true}).waitFor();results.push('Mobile ticket creation, support assignment/resolution, requester closure and reopening');console.log('PASS '+results.at(-1));
 for(const v of [employee,manager])assert.deepEqual(v.errors,[]);assert.deepEqual(serverErrors,[],'No local worker/server errors during the journeys');
 await p.screenshot({path:'.local/workflows-mobile.png',fullPage:true});
 await p.goto('http://127.0.0.1:3055/my-work');await p.getByText(/My tasks \(/).waitFor();assert.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1));
 results.push('Mobile My work overview and no browser runtime errors');console.log('PASS '+results.at(-1));
})().catch(async e=>{console.error(e);for(const [i,p] of pages.entries()){console.log('Page',i,p.url(),(await p.locator('body').innerText()).slice(-2200));await p.screenshot({path:`.local/workflow-mobile-failure-${i}.png`});}process.exitCode=1;}).finally(async()=>{fs.writeFileSync('.local/workflow-mobile-results.json',JSON.stringify({passed:results,failed:!!process.exitCode,physicalDeviceTested:false,at:new Date().toISOString()},null,2));if(browser)await browser.close();});
